/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.fens.desktopMonitor.factory;

import java.sql.Connection;
import com.fens.desktopMonitor.dao.*;
import com.fens.desktopMonitor.jdbc.*;

public class ComprobantefiscalDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return ComprobantefiscalDao
	 */
	public static ComprobantefiscalDao create()
	{
		return new ComprobantefiscalDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return ComprobantefiscalDao
	 */
	public static ComprobantefiscalDao create(Connection conn)
	{
		return new ComprobantefiscalDaoImpl( conn );
	}

}
