/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.fens.desktopMonitor.dto;

import com.fens.desktopMonitor.dao.*;
import com.fens.desktopMonitor.factory.*;
import com.fens.desktopMonitor.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Configuracion implements Serializable
{
	/** 
	 * This attribute maps to the column IDCONFIFURACION in the CONFIGURACION table.
	 */
	protected int idconfifuracion;

	/** 
	 * This attribute represents whether the attribute idconfifuracion has been modified since being read from the database.
	 */
	protected boolean idconfifuracionModified = false;

	/** 
	 * This attribute maps to the column RUTAORIGENPROCESAR in the CONFIGURACION table.
	 */
	protected String rutaorigenprocesar;

	/** 
	 * This attribute represents whether the attribute rutaorigenprocesar has been modified since being read from the database.
	 */
	protected boolean rutaorigenprocesarModified = false;

	/** 
	 * This attribute maps to the column RUTACARPETAEJECUCION in the CONFIGURACION table.
	 */
	protected String rutacarpetaejecucion;

	/** 
	 * This attribute represents whether the attribute rutacarpetaejecucion has been modified since being read from the database.
	 */
	protected boolean rutacarpetaejecucionModified = false;

	/** 
	 * This attribute maps to the column RUTACARPETAERRORES in the CONFIGURACION table.
	 */
	protected String rutacarpetaerrores;

	/** 
	 * This attribute represents whether the attribute rutacarpetaerrores has been modified since being read from the database.
	 */
	protected boolean rutacarpetaerroresModified = false;

	/** 
	 * This attribute maps to the column RUTACARPETAEXITOSOS in the CONFIGURACION table.
	 */
	protected String rutacarpetaexitosos;

	/** 
	 * This attribute represents whether the attribute rutacarpetaexitosos has been modified since being read from the database.
	 */
	protected boolean rutacarpetaexitososModified = false;

	/** 
	 * This attribute maps to the column RUTAORIGENCANCELACIONESXML in the CONFIGURACION table.
	 */
	protected String rutaorigencancelacionesxml;

	/** 
	 * This attribute represents whether the attribute rutaorigencancelacionesxml has been modified since being read from the database.
	 */
	protected boolean rutaorigencancelacionesxmlModified = false;

	/** 
	 * This attribute maps to the column RUTADESTINOCANCELACIONESXML in the CONFIGURACION table.
	 */
	protected String rutadestinocancelacionesxml;

	/** 
	 * This attribute represents whether the attribute rutadestinocancelacionesxml has been modified since being read from the database.
	 */
	protected boolean rutadestinocancelacionesxmlModified = false;

	/** 
	 * This attribute maps to the column RENAMEARCHIVOSTIMBRADOS in the CONFIGURACION table.
	 */
	protected String renamearchivostimbrados;

	/** 
	 * This attribute represents whether the attribute renamearchivostimbrados has been modified since being read from the database.
	 */
	protected boolean renamearchivostimbradosModified = false;

	/** 
	 * This attribute maps to the column LIGAPAC in the CONFIGURACION table.
	 */
	protected String ligapac;

	/** 
	 * This attribute represents whether the attribute ligapac has been modified since being read from the database.
	 */
	protected boolean ligapacModified = false;

	/** 
	 * This attribute maps to the column USUARIOPAC in the CONFIGURACION table.
	 */
	protected String usuariopac;

	/** 
	 * This attribute represents whether the attribute usuariopac has been modified since being read from the database.
	 */
	protected boolean usuariopacModified = false;

	/** 
	 * This attribute maps to the column PASSPAC in the CONFIGURACION table.
	 */
	protected String passpac;

	/** 
	 * This attribute represents whether the attribute passpac has been modified since being read from the database.
	 */
	protected boolean passpacModified = false;

	/** 
	 * This attribute maps to the column MINUTOSDEMON in the CONFIGURACION table.
	 */
	protected int minutosdemon;

	/** 
	 * This attribute represents whether the primitive attribute minutosdemon is null.
	 */
	protected boolean minutosdemonNull = true;

	/** 
	 * This attribute represents whether the attribute minutosdemon has been modified since being read from the database.
	 */
	protected boolean minutosdemonModified = false;

	/** 
	 * This attribute maps to the column ENVIODECORREO in the CONFIGURACION table.
	 */
	protected int enviodecorreo;

	/** 
	 * This attribute represents whether the primitive attribute enviodecorreo is null.
	 */
	protected boolean enviodecorreoNull = true;

	/** 
	 * This attribute represents whether the attribute enviodecorreo has been modified since being read from the database.
	 */
	protected boolean enviodecorreoModified = false;

	/** 
	 * This attribute maps to the column CORREOREMITENTE in the CONFIGURACION table.
	 */
	protected String correoremitente;

	/** 
	 * This attribute represents whether the attribute correoremitente has been modified since being read from the database.
	 */
	protected boolean correoremitenteModified = false;

	/** 
	 * This attribute maps to the column USUARIOREMITENTE in the CONFIGURACION table.
	 */
	protected String usuarioremitente;

	/** 
	 * This attribute represents whether the attribute usuarioremitente has been modified since being read from the database.
	 */
	protected boolean usuarioremitenteModified = false;

	/** 
	 * This attribute maps to the column DOMINIOSMTP in the CONFIGURACION table.
	 */
	protected String dominiosmtp;

	/** 
	 * This attribute represents whether the attribute dominiosmtp has been modified since being read from the database.
	 */
	protected boolean dominiosmtpModified = false;

	/** 
	 * This attribute maps to the column PUERTOSMTP in the CONFIGURACION table.
	 */
	protected int puertosmtp;

	/** 
	 * This attribute represents whether the primitive attribute puertosmtp is null.
	 */
	protected boolean puertosmtpNull = true;

	/** 
	 * This attribute represents whether the attribute puertosmtp has been modified since being read from the database.
	 */
	protected boolean puertosmtpModified = false;

	/** 
	 * This attribute maps to the column PASSWORDCORREO in the CONFIGURACION table.
	 */
	protected String passwordcorreo;

	/** 
	 * This attribute represents whether the attribute passwordcorreo has been modified since being read from the database.
	 */
	protected boolean passwordcorreoModified = false;

	/** 
	 * This attribute maps to the column AUTENTICACIONSMTP in the CONFIGURACION table.
	 */
	protected int autenticacionsmtp;

	/** 
	 * This attribute represents whether the primitive attribute autenticacionsmtp is null.
	 */
	protected boolean autenticacionsmtpNull = true;

	/** 
	 * This attribute represents whether the attribute autenticacionsmtp has been modified since being read from the database.
	 */
	protected boolean autenticacionsmtpModified = false;

	/** 
	 * This attribute maps to the column DESTINATARIOSFIJOS in the CONFIGURACION table.
	 */
	protected String destinatariosfijos;

	/** 
	 * This attribute represents whether the attribute destinatariosfijos has been modified since being read from the database.
	 */
	protected boolean destinatariosfijosModified = false;

	/** 
	 * This attribute maps to the column ASUNTOCORREO in the CONFIGURACION table.
	 */
	protected String asuntocorreo;

	/** 
	 * This attribute represents whether the attribute asuntocorreo has been modified since being read from the database.
	 */
	protected boolean asuntocorreoModified = false;

	/** 
	 * This attribute maps to the column PLANTILLACORREO in the CONFIGURACION table.
	 */
	protected String plantillacorreo;

	/** 
	 * This attribute represents whether the attribute plantillacorreo has been modified since being read from the database.
	 */
	protected boolean plantillacorreoModified = false;

	/** 
	 * This attribute maps to the column ACTIVARIMPRESION in the CONFIGURACION table.
	 */
	protected int activarimpresion;

	/** 
	 * This attribute represents whether the primitive attribute activarimpresion is null.
	 */
	protected boolean activarimpresionNull = true;

	/** 
	 * This attribute represents whether the attribute activarimpresion has been modified since being read from the database.
	 */
	protected boolean activarimpresionModified = false;

	/** 
	 * This attribute maps to the column IMPRESORAPREDETERMINADA in the CONFIGURACION table.
	 */
	protected String impresorapredeterminada;

	/** 
	 * This attribute represents whether the attribute impresorapredeterminada has been modified since being read from the database.
	 */
	protected boolean impresorapredeterminadaModified = false;

	/** 
	 * This attribute maps to the column ERROR_PAC_ULTIMA_CONN in the CONFIGURACION table.
	 */
	protected int errorPacUltimaConn;

	/** 
	 * This attribute represents whether the primitive attribute errorPacUltimaConn is null.
	 */
	protected boolean errorPacUltimaConnNull = true;

	/** 
	 * This attribute represents whether the attribute errorPacUltimaConn has been modified since being read from the database.
	 */
	protected boolean errorPacUltimaConnModified = false;

	/** 
	 * This attribute maps to the column RUTA_EJECUTABLE_ADOBE_READER in the CONFIGURACION table.
	 */
	protected String rutaEjecutableAdobeReader;

	/** 
	 * This attribute represents whether the attribute rutaEjecutableAdobeReader has been modified since being read from the database.
	 */
	protected boolean rutaEjecutableAdobeReaderModified = false;

	/** 
	 * This attribute maps to the column RUTA_CARPETA_ORIGEN_ECONTABILIDAD in the CONFIGURACION table.
	 */
	protected String rutaCarpetaOrigenEcontabilidad;

	/** 
	 * This attribute represents whether the attribute rutaCarpetaOrigenEcontabilidad has been modified since being read from the database.
	 */
	protected boolean rutaCarpetaOrigenEcontabilidadModified = false;

	/** 
	 * This attribute maps to the column RUTA_CARPETA_DESTINO_ECONTABILIDAD in the CONFIGURACION table.
	 */
	protected String rutaCarpetaDestinoEcontabilidad;

	/** 
	 * This attribute represents whether the attribute rutaCarpetaDestinoEcontabilidad has been modified since being read from the database.
	 */
	protected boolean rutaCarpetaDestinoEcontabilidadModified = false;

	/** 
	 * This attribute maps to the column ORDEN_LECTURA_ARCHIVOS in the CONFIGURACION table.
	 */
	protected int ordenLecturaArchivos;

	/** 
	 * This attribute represents whether the attribute ordenLecturaArchivos has been modified since being read from the database.
	 */
	protected boolean ordenLecturaArchivosModified = false;

	/** 
	 * This attribute maps to the column LOTE_PDF_CONCENTRADO in the CONFIGURACION table.
	 */
	protected int lotePdfConcentrado;

	/** 
	 * This attribute represents whether the attribute lotePdfConcentrado has been modified since being read from the database.
	 */
	protected boolean lotePdfConcentradoModified = false;

	/** 
	 * This attribute maps to the column LOTE_NOTIFICACIONES in the CONFIGURACION table.
	 */
	protected int loteNotificaciones;

	/** 
	 * This attribute represents whether the attribute loteNotificaciones has been modified since being read from the database.
	 */
	protected boolean loteNotificacionesModified = false;

	/** 
	 * This attribute maps to the column RUTA_CARPETA_ORIGEN_PAYPOINT in the CONFIGURACION table.
	 */
	protected String rutaCarpetaOrigenPaypoint;

	/** 
	 * This attribute represents whether the attribute rutaCarpetaOrigenPaypoint has been modified since being read from the database.
	 */
	protected boolean rutaCarpetaOrigenPaypointModified = false;

	/** 
	 * This attribute maps to the column RUTA_CARPETA_DESTINO_PAYPOINT in the CONFIGURACION table.
	 */
	protected String rutaCarpetaDestinoPaypoint;

	/** 
	 * This attribute represents whether the attribute rutaCarpetaDestinoPaypoint has been modified since being read from the database.
	 */
	protected boolean rutaCarpetaDestinoPaypointModified = false;

	/**
	 * Method 'Configuracion'
	 * 
	 */
	public Configuracion()
	{
	}

	/**
	 * Method 'getIdconfifuracion'
	 * 
	 * @return int
	 */
	public int getIdconfifuracion()
	{
		return idconfifuracion;
	}

	/**
	 * Method 'setIdconfifuracion'
	 * 
	 * @param idconfifuracion
	 */
	public void setIdconfifuracion(int idconfifuracion)
	{
		this.idconfifuracion = idconfifuracion;
		this.idconfifuracionModified = true;
	}

	/** 
	 * Sets the value of idconfifuracionModified
	 */
	public void setIdconfifuracionModified(boolean idconfifuracionModified)
	{
		this.idconfifuracionModified = idconfifuracionModified;
	}

	/** 
	 * Gets the value of idconfifuracionModified
	 */
	public boolean isIdconfifuracionModified()
	{
		return idconfifuracionModified;
	}

	/**
	 * Method 'getRutaorigenprocesar'
	 * 
	 * @return String
	 */
	public String getRutaorigenprocesar()
	{
		return rutaorigenprocesar;
	}

	/**
	 * Method 'setRutaorigenprocesar'
	 * 
	 * @param rutaorigenprocesar
	 */
	public void setRutaorigenprocesar(String rutaorigenprocesar)
	{
		this.rutaorigenprocesar = rutaorigenprocesar;
		this.rutaorigenprocesarModified = true;
	}

	/** 
	 * Sets the value of rutaorigenprocesarModified
	 */
	public void setRutaorigenprocesarModified(boolean rutaorigenprocesarModified)
	{
		this.rutaorigenprocesarModified = rutaorigenprocesarModified;
	}

	/** 
	 * Gets the value of rutaorigenprocesarModified
	 */
	public boolean isRutaorigenprocesarModified()
	{
		return rutaorigenprocesarModified;
	}

	/**
	 * Method 'getRutacarpetaejecucion'
	 * 
	 * @return String
	 */
	public String getRutacarpetaejecucion()
	{
		return rutacarpetaejecucion;
	}

	/**
	 * Method 'setRutacarpetaejecucion'
	 * 
	 * @param rutacarpetaejecucion
	 */
	public void setRutacarpetaejecucion(String rutacarpetaejecucion)
	{
		this.rutacarpetaejecucion = rutacarpetaejecucion;
		this.rutacarpetaejecucionModified = true;
	}

	/** 
	 * Sets the value of rutacarpetaejecucionModified
	 */
	public void setRutacarpetaejecucionModified(boolean rutacarpetaejecucionModified)
	{
		this.rutacarpetaejecucionModified = rutacarpetaejecucionModified;
	}

	/** 
	 * Gets the value of rutacarpetaejecucionModified
	 */
	public boolean isRutacarpetaejecucionModified()
	{
		return rutacarpetaejecucionModified;
	}

	/**
	 * Method 'getRutacarpetaerrores'
	 * 
	 * @return String
	 */
	public String getRutacarpetaerrores()
	{
		return rutacarpetaerrores;
	}

	/**
	 * Method 'setRutacarpetaerrores'
	 * 
	 * @param rutacarpetaerrores
	 */
	public void setRutacarpetaerrores(String rutacarpetaerrores)
	{
		this.rutacarpetaerrores = rutacarpetaerrores;
		this.rutacarpetaerroresModified = true;
	}

	/** 
	 * Sets the value of rutacarpetaerroresModified
	 */
	public void setRutacarpetaerroresModified(boolean rutacarpetaerroresModified)
	{
		this.rutacarpetaerroresModified = rutacarpetaerroresModified;
	}

	/** 
	 * Gets the value of rutacarpetaerroresModified
	 */
	public boolean isRutacarpetaerroresModified()
	{
		return rutacarpetaerroresModified;
	}

	/**
	 * Method 'getRutacarpetaexitosos'
	 * 
	 * @return String
	 */
	public String getRutacarpetaexitosos()
	{
		return rutacarpetaexitosos;
	}

	/**
	 * Method 'setRutacarpetaexitosos'
	 * 
	 * @param rutacarpetaexitosos
	 */
	public void setRutacarpetaexitosos(String rutacarpetaexitosos)
	{
		this.rutacarpetaexitosos = rutacarpetaexitosos;
		this.rutacarpetaexitososModified = true;
	}

	/** 
	 * Sets the value of rutacarpetaexitososModified
	 */
	public void setRutacarpetaexitososModified(boolean rutacarpetaexitososModified)
	{
		this.rutacarpetaexitososModified = rutacarpetaexitososModified;
	}

	/** 
	 * Gets the value of rutacarpetaexitososModified
	 */
	public boolean isRutacarpetaexitososModified()
	{
		return rutacarpetaexitososModified;
	}

	/**
	 * Method 'getRutaorigencancelacionesxml'
	 * 
	 * @return String
	 */
	public String getRutaorigencancelacionesxml()
	{
		return rutaorigencancelacionesxml;
	}

	/**
	 * Method 'setRutaorigencancelacionesxml'
	 * 
	 * @param rutaorigencancelacionesxml
	 */
	public void setRutaorigencancelacionesxml(String rutaorigencancelacionesxml)
	{
		this.rutaorigencancelacionesxml = rutaorigencancelacionesxml;
		this.rutaorigencancelacionesxmlModified = true;
	}

	/** 
	 * Sets the value of rutaorigencancelacionesxmlModified
	 */
	public void setRutaorigencancelacionesxmlModified(boolean rutaorigencancelacionesxmlModified)
	{
		this.rutaorigencancelacionesxmlModified = rutaorigencancelacionesxmlModified;
	}

	/** 
	 * Gets the value of rutaorigencancelacionesxmlModified
	 */
	public boolean isRutaorigencancelacionesxmlModified()
	{
		return rutaorigencancelacionesxmlModified;
	}

	/**
	 * Method 'getRutadestinocancelacionesxml'
	 * 
	 * @return String
	 */
	public String getRutadestinocancelacionesxml()
	{
		return rutadestinocancelacionesxml;
	}

	/**
	 * Method 'setRutadestinocancelacionesxml'
	 * 
	 * @param rutadestinocancelacionesxml
	 */
	public void setRutadestinocancelacionesxml(String rutadestinocancelacionesxml)
	{
		this.rutadestinocancelacionesxml = rutadestinocancelacionesxml;
		this.rutadestinocancelacionesxmlModified = true;
	}

	/** 
	 * Sets the value of rutadestinocancelacionesxmlModified
	 */
	public void setRutadestinocancelacionesxmlModified(boolean rutadestinocancelacionesxmlModified)
	{
		this.rutadestinocancelacionesxmlModified = rutadestinocancelacionesxmlModified;
	}

	/** 
	 * Gets the value of rutadestinocancelacionesxmlModified
	 */
	public boolean isRutadestinocancelacionesxmlModified()
	{
		return rutadestinocancelacionesxmlModified;
	}

	/**
	 * Method 'getRenamearchivostimbrados'
	 * 
	 * @return String
	 */
	public String getRenamearchivostimbrados()
	{
		return renamearchivostimbrados;
	}

	/**
	 * Method 'setRenamearchivostimbrados'
	 * 
	 * @param renamearchivostimbrados
	 */
	public void setRenamearchivostimbrados(String renamearchivostimbrados)
	{
		this.renamearchivostimbrados = renamearchivostimbrados;
		this.renamearchivostimbradosModified = true;
	}

	/** 
	 * Sets the value of renamearchivostimbradosModified
	 */
	public void setRenamearchivostimbradosModified(boolean renamearchivostimbradosModified)
	{
		this.renamearchivostimbradosModified = renamearchivostimbradosModified;
	}

	/** 
	 * Gets the value of renamearchivostimbradosModified
	 */
	public boolean isRenamearchivostimbradosModified()
	{
		return renamearchivostimbradosModified;
	}

	/**
	 * Method 'getLigapac'
	 * 
	 * @return String
	 */
	public String getLigapac()
	{
		return ligapac;
	}

	/**
	 * Method 'setLigapac'
	 * 
	 * @param ligapac
	 */
	public void setLigapac(String ligapac)
	{
		this.ligapac = ligapac;
		this.ligapacModified = true;
	}

	/** 
	 * Sets the value of ligapacModified
	 */
	public void setLigapacModified(boolean ligapacModified)
	{
		this.ligapacModified = ligapacModified;
	}

	/** 
	 * Gets the value of ligapacModified
	 */
	public boolean isLigapacModified()
	{
		return ligapacModified;
	}

	/**
	 * Method 'getUsuariopac'
	 * 
	 * @return String
	 */
	public String getUsuariopac()
	{
		return usuariopac;
	}

	/**
	 * Method 'setUsuariopac'
	 * 
	 * @param usuariopac
	 */
	public void setUsuariopac(String usuariopac)
	{
		this.usuariopac = usuariopac;
		this.usuariopacModified = true;
	}

	/** 
	 * Sets the value of usuariopacModified
	 */
	public void setUsuariopacModified(boolean usuariopacModified)
	{
		this.usuariopacModified = usuariopacModified;
	}

	/** 
	 * Gets the value of usuariopacModified
	 */
	public boolean isUsuariopacModified()
	{
		return usuariopacModified;
	}

	/**
	 * Method 'getPasspac'
	 * 
	 * @return String
	 */
	public String getPasspac()
	{
		return passpac;
	}

	/**
	 * Method 'setPasspac'
	 * 
	 * @param passpac
	 */
	public void setPasspac(String passpac)
	{
		this.passpac = passpac;
		this.passpacModified = true;
	}

	/** 
	 * Sets the value of passpacModified
	 */
	public void setPasspacModified(boolean passpacModified)
	{
		this.passpacModified = passpacModified;
	}

	/** 
	 * Gets the value of passpacModified
	 */
	public boolean isPasspacModified()
	{
		return passpacModified;
	}

	/**
	 * Method 'getMinutosdemon'
	 * 
	 * @return int
	 */
	public int getMinutosdemon()
	{
		return minutosdemon;
	}

	/**
	 * Method 'setMinutosdemon'
	 * 
	 * @param minutosdemon
	 */
	public void setMinutosdemon(int minutosdemon)
	{
		this.minutosdemon = minutosdemon;
		this.minutosdemonNull = false;
		this.minutosdemonModified = true;
	}

	/**
	 * Method 'setMinutosdemonNull'
	 * 
	 * @param value
	 */
	public void setMinutosdemonNull(boolean value)
	{
		this.minutosdemonNull = value;
		this.minutosdemonModified = true;
	}

	/**
	 * Method 'isMinutosdemonNull'
	 * 
	 * @return boolean
	 */
	public boolean isMinutosdemonNull()
	{
		return minutosdemonNull;
	}

	/** 
	 * Sets the value of minutosdemonModified
	 */
	public void setMinutosdemonModified(boolean minutosdemonModified)
	{
		this.minutosdemonModified = minutosdemonModified;
	}

	/** 
	 * Gets the value of minutosdemonModified
	 */
	public boolean isMinutosdemonModified()
	{
		return minutosdemonModified;
	}

	/**
	 * Method 'getEnviodecorreo'
	 * 
	 * @return int
	 */
	public int getEnviodecorreo()
	{
		return enviodecorreo;
	}

	/**
	 * Method 'setEnviodecorreo'
	 * 
	 * @param enviodecorreo
	 */
	public void setEnviodecorreo(int enviodecorreo)
	{
		this.enviodecorreo = enviodecorreo;
		this.enviodecorreoNull = false;
		this.enviodecorreoModified = true;
	}

	/**
	 * Method 'setEnviodecorreoNull'
	 * 
	 * @param value
	 */
	public void setEnviodecorreoNull(boolean value)
	{
		this.enviodecorreoNull = value;
		this.enviodecorreoModified = true;
	}

	/**
	 * Method 'isEnviodecorreoNull'
	 * 
	 * @return boolean
	 */
	public boolean isEnviodecorreoNull()
	{
		return enviodecorreoNull;
	}

	/** 
	 * Sets the value of enviodecorreoModified
	 */
	public void setEnviodecorreoModified(boolean enviodecorreoModified)
	{
		this.enviodecorreoModified = enviodecorreoModified;
	}

	/** 
	 * Gets the value of enviodecorreoModified
	 */
	public boolean isEnviodecorreoModified()
	{
		return enviodecorreoModified;
	}

	/**
	 * Method 'getCorreoremitente'
	 * 
	 * @return String
	 */
	public String getCorreoremitente()
	{
		return correoremitente;
	}

	/**
	 * Method 'setCorreoremitente'
	 * 
	 * @param correoremitente
	 */
	public void setCorreoremitente(String correoremitente)
	{
		this.correoremitente = correoremitente;
		this.correoremitenteModified = true;
	}

	/** 
	 * Sets the value of correoremitenteModified
	 */
	public void setCorreoremitenteModified(boolean correoremitenteModified)
	{
		this.correoremitenteModified = correoremitenteModified;
	}

	/** 
	 * Gets the value of correoremitenteModified
	 */
	public boolean isCorreoremitenteModified()
	{
		return correoremitenteModified;
	}

	/**
	 * Method 'getUsuarioremitente'
	 * 
	 * @return String
	 */
	public String getUsuarioremitente()
	{
		return usuarioremitente;
	}

	/**
	 * Method 'setUsuarioremitente'
	 * 
	 * @param usuarioremitente
	 */
	public void setUsuarioremitente(String usuarioremitente)
	{
		this.usuarioremitente = usuarioremitente;
		this.usuarioremitenteModified = true;
	}

	/** 
	 * Sets the value of usuarioremitenteModified
	 */
	public void setUsuarioremitenteModified(boolean usuarioremitenteModified)
	{
		this.usuarioremitenteModified = usuarioremitenteModified;
	}

	/** 
	 * Gets the value of usuarioremitenteModified
	 */
	public boolean isUsuarioremitenteModified()
	{
		return usuarioremitenteModified;
	}

	/**
	 * Method 'getDominiosmtp'
	 * 
	 * @return String
	 */
	public String getDominiosmtp()
	{
		return dominiosmtp;
	}

	/**
	 * Method 'setDominiosmtp'
	 * 
	 * @param dominiosmtp
	 */
	public void setDominiosmtp(String dominiosmtp)
	{
		this.dominiosmtp = dominiosmtp;
		this.dominiosmtpModified = true;
	}

	/** 
	 * Sets the value of dominiosmtpModified
	 */
	public void setDominiosmtpModified(boolean dominiosmtpModified)
	{
		this.dominiosmtpModified = dominiosmtpModified;
	}

	/** 
	 * Gets the value of dominiosmtpModified
	 */
	public boolean isDominiosmtpModified()
	{
		return dominiosmtpModified;
	}

	/**
	 * Method 'getPuertosmtp'
	 * 
	 * @return int
	 */
	public int getPuertosmtp()
	{
		return puertosmtp;
	}

	/**
	 * Method 'setPuertosmtp'
	 * 
	 * @param puertosmtp
	 */
	public void setPuertosmtp(int puertosmtp)
	{
		this.puertosmtp = puertosmtp;
		this.puertosmtpNull = false;
		this.puertosmtpModified = true;
	}

	/**
	 * Method 'setPuertosmtpNull'
	 * 
	 * @param value
	 */
	public void setPuertosmtpNull(boolean value)
	{
		this.puertosmtpNull = value;
		this.puertosmtpModified = true;
	}

	/**
	 * Method 'isPuertosmtpNull'
	 * 
	 * @return boolean
	 */
	public boolean isPuertosmtpNull()
	{
		return puertosmtpNull;
	}

	/** 
	 * Sets the value of puertosmtpModified
	 */
	public void setPuertosmtpModified(boolean puertosmtpModified)
	{
		this.puertosmtpModified = puertosmtpModified;
	}

	/** 
	 * Gets the value of puertosmtpModified
	 */
	public boolean isPuertosmtpModified()
	{
		return puertosmtpModified;
	}

	/**
	 * Method 'getPasswordcorreo'
	 * 
	 * @return String
	 */
	public String getPasswordcorreo()
	{
		return passwordcorreo;
	}

	/**
	 * Method 'setPasswordcorreo'
	 * 
	 * @param passwordcorreo
	 */
	public void setPasswordcorreo(String passwordcorreo)
	{
		this.passwordcorreo = passwordcorreo;
		this.passwordcorreoModified = true;
	}

	/** 
	 * Sets the value of passwordcorreoModified
	 */
	public void setPasswordcorreoModified(boolean passwordcorreoModified)
	{
		this.passwordcorreoModified = passwordcorreoModified;
	}

	/** 
	 * Gets the value of passwordcorreoModified
	 */
	public boolean isPasswordcorreoModified()
	{
		return passwordcorreoModified;
	}

	/**
	 * Method 'getAutenticacionsmtp'
	 * 
	 * @return int
	 */
	public int getAutenticacionsmtp()
	{
		return autenticacionsmtp;
	}

	/**
	 * Method 'setAutenticacionsmtp'
	 * 
	 * @param autenticacionsmtp
	 */
	public void setAutenticacionsmtp(int autenticacionsmtp)
	{
		this.autenticacionsmtp = autenticacionsmtp;
		this.autenticacionsmtpNull = false;
		this.autenticacionsmtpModified = true;
	}

	/**
	 * Method 'setAutenticacionsmtpNull'
	 * 
	 * @param value
	 */
	public void setAutenticacionsmtpNull(boolean value)
	{
		this.autenticacionsmtpNull = value;
		this.autenticacionsmtpModified = true;
	}

	/**
	 * Method 'isAutenticacionsmtpNull'
	 * 
	 * @return boolean
	 */
	public boolean isAutenticacionsmtpNull()
	{
		return autenticacionsmtpNull;
	}

	/** 
	 * Sets the value of autenticacionsmtpModified
	 */
	public void setAutenticacionsmtpModified(boolean autenticacionsmtpModified)
	{
		this.autenticacionsmtpModified = autenticacionsmtpModified;
	}

	/** 
	 * Gets the value of autenticacionsmtpModified
	 */
	public boolean isAutenticacionsmtpModified()
	{
		return autenticacionsmtpModified;
	}

	/**
	 * Method 'getDestinatariosfijos'
	 * 
	 * @return String
	 */
	public String getDestinatariosfijos()
	{
		return destinatariosfijos;
	}

	/**
	 * Method 'setDestinatariosfijos'
	 * 
	 * @param destinatariosfijos
	 */
	public void setDestinatariosfijos(String destinatariosfijos)
	{
		this.destinatariosfijos = destinatariosfijos;
		this.destinatariosfijosModified = true;
	}

	/** 
	 * Sets the value of destinatariosfijosModified
	 */
	public void setDestinatariosfijosModified(boolean destinatariosfijosModified)
	{
		this.destinatariosfijosModified = destinatariosfijosModified;
	}

	/** 
	 * Gets the value of destinatariosfijosModified
	 */
	public boolean isDestinatariosfijosModified()
	{
		return destinatariosfijosModified;
	}

	/**
	 * Method 'getAsuntocorreo'
	 * 
	 * @return String
	 */
	public String getAsuntocorreo()
	{
		return asuntocorreo;
	}

	/**
	 * Method 'setAsuntocorreo'
	 * 
	 * @param asuntocorreo
	 */
	public void setAsuntocorreo(String asuntocorreo)
	{
		this.asuntocorreo = asuntocorreo;
		this.asuntocorreoModified = true;
	}

	/** 
	 * Sets the value of asuntocorreoModified
	 */
	public void setAsuntocorreoModified(boolean asuntocorreoModified)
	{
		this.asuntocorreoModified = asuntocorreoModified;
	}

	/** 
	 * Gets the value of asuntocorreoModified
	 */
	public boolean isAsuntocorreoModified()
	{
		return asuntocorreoModified;
	}

	/**
	 * Method 'getPlantillacorreo'
	 * 
	 * @return String
	 */
	public String getPlantillacorreo()
	{
		return plantillacorreo;
	}

	/**
	 * Method 'setPlantillacorreo'
	 * 
	 * @param plantillacorreo
	 */
	public void setPlantillacorreo(String plantillacorreo)
	{
		this.plantillacorreo = plantillacorreo;
		this.plantillacorreoModified = true;
	}

	/** 
	 * Sets the value of plantillacorreoModified
	 */
	public void setPlantillacorreoModified(boolean plantillacorreoModified)
	{
		this.plantillacorreoModified = plantillacorreoModified;
	}

	/** 
	 * Gets the value of plantillacorreoModified
	 */
	public boolean isPlantillacorreoModified()
	{
		return plantillacorreoModified;
	}

	/**
	 * Method 'getActivarimpresion'
	 * 
	 * @return int
	 */
	public int getActivarimpresion()
	{
		return activarimpresion;
	}

	/**
	 * Method 'setActivarimpresion'
	 * 
	 * @param activarimpresion
	 */
	public void setActivarimpresion(int activarimpresion)
	{
		this.activarimpresion = activarimpresion;
		this.activarimpresionNull = false;
		this.activarimpresionModified = true;
	}

	/**
	 * Method 'setActivarimpresionNull'
	 * 
	 * @param value
	 */
	public void setActivarimpresionNull(boolean value)
	{
		this.activarimpresionNull = value;
		this.activarimpresionModified = true;
	}

	/**
	 * Method 'isActivarimpresionNull'
	 * 
	 * @return boolean
	 */
	public boolean isActivarimpresionNull()
	{
		return activarimpresionNull;
	}

	/** 
	 * Sets the value of activarimpresionModified
	 */
	public void setActivarimpresionModified(boolean activarimpresionModified)
	{
		this.activarimpresionModified = activarimpresionModified;
	}

	/** 
	 * Gets the value of activarimpresionModified
	 */
	public boolean isActivarimpresionModified()
	{
		return activarimpresionModified;
	}

	/**
	 * Method 'getImpresorapredeterminada'
	 * 
	 * @return String
	 */
	public String getImpresorapredeterminada()
	{
		return impresorapredeterminada;
	}

	/**
	 * Method 'setImpresorapredeterminada'
	 * 
	 * @param impresorapredeterminada
	 */
	public void setImpresorapredeterminada(String impresorapredeterminada)
	{
		this.impresorapredeterminada = impresorapredeterminada;
		this.impresorapredeterminadaModified = true;
	}

	/** 
	 * Sets the value of impresorapredeterminadaModified
	 */
	public void setImpresorapredeterminadaModified(boolean impresorapredeterminadaModified)
	{
		this.impresorapredeterminadaModified = impresorapredeterminadaModified;
	}

	/** 
	 * Gets the value of impresorapredeterminadaModified
	 */
	public boolean isImpresorapredeterminadaModified()
	{
		return impresorapredeterminadaModified;
	}

	/**
	 * Method 'getErrorPacUltimaConn'
	 * 
	 * @return int
	 */
	public int getErrorPacUltimaConn()
	{
		return errorPacUltimaConn;
	}

	/**
	 * Method 'setErrorPacUltimaConn'
	 * 
	 * @param errorPacUltimaConn
	 */
	public void setErrorPacUltimaConn(int errorPacUltimaConn)
	{
		this.errorPacUltimaConn = errorPacUltimaConn;
		this.errorPacUltimaConnNull = false;
		this.errorPacUltimaConnModified = true;
	}

	/**
	 * Method 'setErrorPacUltimaConnNull'
	 * 
	 * @param value
	 */
	public void setErrorPacUltimaConnNull(boolean value)
	{
		this.errorPacUltimaConnNull = value;
		this.errorPacUltimaConnModified = true;
	}

	/**
	 * Method 'isErrorPacUltimaConnNull'
	 * 
	 * @return boolean
	 */
	public boolean isErrorPacUltimaConnNull()
	{
		return errorPacUltimaConnNull;
	}

	/** 
	 * Sets the value of errorPacUltimaConnModified
	 */
	public void setErrorPacUltimaConnModified(boolean errorPacUltimaConnModified)
	{
		this.errorPacUltimaConnModified = errorPacUltimaConnModified;
	}

	/** 
	 * Gets the value of errorPacUltimaConnModified
	 */
	public boolean isErrorPacUltimaConnModified()
	{
		return errorPacUltimaConnModified;
	}

	/**
	 * Method 'getRutaEjecutableAdobeReader'
	 * 
	 * @return String
	 */
	public String getRutaEjecutableAdobeReader()
	{
		return rutaEjecutableAdobeReader;
	}

	/**
	 * Method 'setRutaEjecutableAdobeReader'
	 * 
	 * @param rutaEjecutableAdobeReader
	 */
	public void setRutaEjecutableAdobeReader(String rutaEjecutableAdobeReader)
	{
		this.rutaEjecutableAdobeReader = rutaEjecutableAdobeReader;
		this.rutaEjecutableAdobeReaderModified = true;
	}

	/** 
	 * Sets the value of rutaEjecutableAdobeReaderModified
	 */
	public void setRutaEjecutableAdobeReaderModified(boolean rutaEjecutableAdobeReaderModified)
	{
		this.rutaEjecutableAdobeReaderModified = rutaEjecutableAdobeReaderModified;
	}

	/** 
	 * Gets the value of rutaEjecutableAdobeReaderModified
	 */
	public boolean isRutaEjecutableAdobeReaderModified()
	{
		return rutaEjecutableAdobeReaderModified;
	}

	/**
	 * Method 'getRutaCarpetaOrigenEcontabilidad'
	 * 
	 * @return String
	 */
	public String getRutaCarpetaOrigenEcontabilidad()
	{
		return rutaCarpetaOrigenEcontabilidad;
	}

	/**
	 * Method 'setRutaCarpetaOrigenEcontabilidad'
	 * 
	 * @param rutaCarpetaOrigenEcontabilidad
	 */
	public void setRutaCarpetaOrigenEcontabilidad(String rutaCarpetaOrigenEcontabilidad)
	{
		this.rutaCarpetaOrigenEcontabilidad = rutaCarpetaOrigenEcontabilidad;
		this.rutaCarpetaOrigenEcontabilidadModified = true;
	}

	/** 
	 * Sets the value of rutaCarpetaOrigenEcontabilidadModified
	 */
	public void setRutaCarpetaOrigenEcontabilidadModified(boolean rutaCarpetaOrigenEcontabilidadModified)
	{
		this.rutaCarpetaOrigenEcontabilidadModified = rutaCarpetaOrigenEcontabilidadModified;
	}

	/** 
	 * Gets the value of rutaCarpetaOrigenEcontabilidadModified
	 */
	public boolean isRutaCarpetaOrigenEcontabilidadModified()
	{
		return rutaCarpetaOrigenEcontabilidadModified;
	}

	/**
	 * Method 'getRutaCarpetaDestinoEcontabilidad'
	 * 
	 * @return String
	 */
	public String getRutaCarpetaDestinoEcontabilidad()
	{
		return rutaCarpetaDestinoEcontabilidad;
	}

	/**
	 * Method 'setRutaCarpetaDestinoEcontabilidad'
	 * 
	 * @param rutaCarpetaDestinoEcontabilidad
	 */
	public void setRutaCarpetaDestinoEcontabilidad(String rutaCarpetaDestinoEcontabilidad)
	{
		this.rutaCarpetaDestinoEcontabilidad = rutaCarpetaDestinoEcontabilidad;
		this.rutaCarpetaDestinoEcontabilidadModified = true;
	}

	/** 
	 * Sets the value of rutaCarpetaDestinoEcontabilidadModified
	 */
	public void setRutaCarpetaDestinoEcontabilidadModified(boolean rutaCarpetaDestinoEcontabilidadModified)
	{
		this.rutaCarpetaDestinoEcontabilidadModified = rutaCarpetaDestinoEcontabilidadModified;
	}

	/** 
	 * Gets the value of rutaCarpetaDestinoEcontabilidadModified
	 */
	public boolean isRutaCarpetaDestinoEcontabilidadModified()
	{
		return rutaCarpetaDestinoEcontabilidadModified;
	}

	/**
	 * Method 'getOrdenLecturaArchivos'
	 * 
	 * @return int
	 */
	public int getOrdenLecturaArchivos()
	{
		return ordenLecturaArchivos;
	}

	/**
	 * Method 'setOrdenLecturaArchivos'
	 * 
	 * @param ordenLecturaArchivos
	 */
	public void setOrdenLecturaArchivos(int ordenLecturaArchivos)
	{
		this.ordenLecturaArchivos = ordenLecturaArchivos;
		this.ordenLecturaArchivosModified = true;
	}

	/** 
	 * Sets the value of ordenLecturaArchivosModified
	 */
	public void setOrdenLecturaArchivosModified(boolean ordenLecturaArchivosModified)
	{
		this.ordenLecturaArchivosModified = ordenLecturaArchivosModified;
	}

	/** 
	 * Gets the value of ordenLecturaArchivosModified
	 */
	public boolean isOrdenLecturaArchivosModified()
	{
		return ordenLecturaArchivosModified;
	}

	/**
	 * Method 'getLotePdfConcentrado'
	 * 
	 * @return int
	 */
	public int getLotePdfConcentrado()
	{
		return lotePdfConcentrado;
	}

	/**
	 * Method 'setLotePdfConcentrado'
	 * 
	 * @param lotePdfConcentrado
	 */
	public void setLotePdfConcentrado(int lotePdfConcentrado)
	{
		this.lotePdfConcentrado = lotePdfConcentrado;
		this.lotePdfConcentradoModified = true;
	}

	/** 
	 * Sets the value of lotePdfConcentradoModified
	 */
	public void setLotePdfConcentradoModified(boolean lotePdfConcentradoModified)
	{
		this.lotePdfConcentradoModified = lotePdfConcentradoModified;
	}

	/** 
	 * Gets the value of lotePdfConcentradoModified
	 */
	public boolean isLotePdfConcentradoModified()
	{
		return lotePdfConcentradoModified;
	}

	/**
	 * Method 'getLoteNotificaciones'
	 * 
	 * @return int
	 */
	public int getLoteNotificaciones()
	{
		return loteNotificaciones;
	}

	/**
	 * Method 'setLoteNotificaciones'
	 * 
	 * @param loteNotificaciones
	 */
	public void setLoteNotificaciones(int loteNotificaciones)
	{
		this.loteNotificaciones = loteNotificaciones;
		this.loteNotificacionesModified = true;
	}

	/** 
	 * Sets the value of loteNotificacionesModified
	 */
	public void setLoteNotificacionesModified(boolean loteNotificacionesModified)
	{
		this.loteNotificacionesModified = loteNotificacionesModified;
	}

	/** 
	 * Gets the value of loteNotificacionesModified
	 */
	public boolean isLoteNotificacionesModified()
	{
		return loteNotificacionesModified;
	}

	/**
	 * Method 'getRutaCarpetaOrigenPaypoint'
	 * 
	 * @return String
	 */
	public String getRutaCarpetaOrigenPaypoint()
	{
		return rutaCarpetaOrigenPaypoint;
	}

	/**
	 * Method 'setRutaCarpetaOrigenPaypoint'
	 * 
	 * @param rutaCarpetaOrigenPaypoint
	 */
	public void setRutaCarpetaOrigenPaypoint(String rutaCarpetaOrigenPaypoint)
	{
		this.rutaCarpetaOrigenPaypoint = rutaCarpetaOrigenPaypoint;
		this.rutaCarpetaOrigenPaypointModified = true;
	}

	/** 
	 * Sets the value of rutaCarpetaOrigenPaypointModified
	 */
	public void setRutaCarpetaOrigenPaypointModified(boolean rutaCarpetaOrigenPaypointModified)
	{
		this.rutaCarpetaOrigenPaypointModified = rutaCarpetaOrigenPaypointModified;
	}

	/** 
	 * Gets the value of rutaCarpetaOrigenPaypointModified
	 */
	public boolean isRutaCarpetaOrigenPaypointModified()
	{
		return rutaCarpetaOrigenPaypointModified;
	}

	/**
	 * Method 'getRutaCarpetaDestinoPaypoint'
	 * 
	 * @return String
	 */
	public String getRutaCarpetaDestinoPaypoint()
	{
		return rutaCarpetaDestinoPaypoint;
	}

	/**
	 * Method 'setRutaCarpetaDestinoPaypoint'
	 * 
	 * @param rutaCarpetaDestinoPaypoint
	 */
	public void setRutaCarpetaDestinoPaypoint(String rutaCarpetaDestinoPaypoint)
	{
		this.rutaCarpetaDestinoPaypoint = rutaCarpetaDestinoPaypoint;
		this.rutaCarpetaDestinoPaypointModified = true;
	}

	/** 
	 * Sets the value of rutaCarpetaDestinoPaypointModified
	 */
	public void setRutaCarpetaDestinoPaypointModified(boolean rutaCarpetaDestinoPaypointModified)
	{
		this.rutaCarpetaDestinoPaypointModified = rutaCarpetaDestinoPaypointModified;
	}

	/** 
	 * Gets the value of rutaCarpetaDestinoPaypointModified
	 */
	public boolean isRutaCarpetaDestinoPaypointModified()
	{
		return rutaCarpetaDestinoPaypointModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Configuracion)) {
			return false;
		}
		
		final Configuracion _cast = (Configuracion) _other;
		if (idconfifuracion != _cast.idconfifuracion) {
			return false;
		}
		
		if (idconfifuracionModified != _cast.idconfifuracionModified) {
			return false;
		}
		
		if (rutaorigenprocesar == null ? _cast.rutaorigenprocesar != rutaorigenprocesar : !rutaorigenprocesar.equals( _cast.rutaorigenprocesar )) {
			return false;
		}
		
		if (rutaorigenprocesarModified != _cast.rutaorigenprocesarModified) {
			return false;
		}
		
		if (rutacarpetaejecucion == null ? _cast.rutacarpetaejecucion != rutacarpetaejecucion : !rutacarpetaejecucion.equals( _cast.rutacarpetaejecucion )) {
			return false;
		}
		
		if (rutacarpetaejecucionModified != _cast.rutacarpetaejecucionModified) {
			return false;
		}
		
		if (rutacarpetaerrores == null ? _cast.rutacarpetaerrores != rutacarpetaerrores : !rutacarpetaerrores.equals( _cast.rutacarpetaerrores )) {
			return false;
		}
		
		if (rutacarpetaerroresModified != _cast.rutacarpetaerroresModified) {
			return false;
		}
		
		if (rutacarpetaexitosos == null ? _cast.rutacarpetaexitosos != rutacarpetaexitosos : !rutacarpetaexitosos.equals( _cast.rutacarpetaexitosos )) {
			return false;
		}
		
		if (rutacarpetaexitososModified != _cast.rutacarpetaexitososModified) {
			return false;
		}
		
		if (rutaorigencancelacionesxml == null ? _cast.rutaorigencancelacionesxml != rutaorigencancelacionesxml : !rutaorigencancelacionesxml.equals( _cast.rutaorigencancelacionesxml )) {
			return false;
		}
		
		if (rutaorigencancelacionesxmlModified != _cast.rutaorigencancelacionesxmlModified) {
			return false;
		}
		
		if (rutadestinocancelacionesxml == null ? _cast.rutadestinocancelacionesxml != rutadestinocancelacionesxml : !rutadestinocancelacionesxml.equals( _cast.rutadestinocancelacionesxml )) {
			return false;
		}
		
		if (rutadestinocancelacionesxmlModified != _cast.rutadestinocancelacionesxmlModified) {
			return false;
		}
		
		if (renamearchivostimbrados == null ? _cast.renamearchivostimbrados != renamearchivostimbrados : !renamearchivostimbrados.equals( _cast.renamearchivostimbrados )) {
			return false;
		}
		
		if (renamearchivostimbradosModified != _cast.renamearchivostimbradosModified) {
			return false;
		}
		
		if (ligapac == null ? _cast.ligapac != ligapac : !ligapac.equals( _cast.ligapac )) {
			return false;
		}
		
		if (ligapacModified != _cast.ligapacModified) {
			return false;
		}
		
		if (usuariopac == null ? _cast.usuariopac != usuariopac : !usuariopac.equals( _cast.usuariopac )) {
			return false;
		}
		
		if (usuariopacModified != _cast.usuariopacModified) {
			return false;
		}
		
		if (passpac == null ? _cast.passpac != passpac : !passpac.equals( _cast.passpac )) {
			return false;
		}
		
		if (passpacModified != _cast.passpacModified) {
			return false;
		}
		
		if (minutosdemon != _cast.minutosdemon) {
			return false;
		}
		
		if (minutosdemonNull != _cast.minutosdemonNull) {
			return false;
		}
		
		if (minutosdemonModified != _cast.minutosdemonModified) {
			return false;
		}
		
		if (enviodecorreo != _cast.enviodecorreo) {
			return false;
		}
		
		if (enviodecorreoNull != _cast.enviodecorreoNull) {
			return false;
		}
		
		if (enviodecorreoModified != _cast.enviodecorreoModified) {
			return false;
		}
		
		if (correoremitente == null ? _cast.correoremitente != correoremitente : !correoremitente.equals( _cast.correoremitente )) {
			return false;
		}
		
		if (correoremitenteModified != _cast.correoremitenteModified) {
			return false;
		}
		
		if (usuarioremitente == null ? _cast.usuarioremitente != usuarioremitente : !usuarioremitente.equals( _cast.usuarioremitente )) {
			return false;
		}
		
		if (usuarioremitenteModified != _cast.usuarioremitenteModified) {
			return false;
		}
		
		if (dominiosmtp == null ? _cast.dominiosmtp != dominiosmtp : !dominiosmtp.equals( _cast.dominiosmtp )) {
			return false;
		}
		
		if (dominiosmtpModified != _cast.dominiosmtpModified) {
			return false;
		}
		
		if (puertosmtp != _cast.puertosmtp) {
			return false;
		}
		
		if (puertosmtpNull != _cast.puertosmtpNull) {
			return false;
		}
		
		if (puertosmtpModified != _cast.puertosmtpModified) {
			return false;
		}
		
		if (passwordcorreo == null ? _cast.passwordcorreo != passwordcorreo : !passwordcorreo.equals( _cast.passwordcorreo )) {
			return false;
		}
		
		if (passwordcorreoModified != _cast.passwordcorreoModified) {
			return false;
		}
		
		if (autenticacionsmtp != _cast.autenticacionsmtp) {
			return false;
		}
		
		if (autenticacionsmtpNull != _cast.autenticacionsmtpNull) {
			return false;
		}
		
		if (autenticacionsmtpModified != _cast.autenticacionsmtpModified) {
			return false;
		}
		
		if (destinatariosfijos == null ? _cast.destinatariosfijos != destinatariosfijos : !destinatariosfijos.equals( _cast.destinatariosfijos )) {
			return false;
		}
		
		if (destinatariosfijosModified != _cast.destinatariosfijosModified) {
			return false;
		}
		
		if (asuntocorreo == null ? _cast.asuntocorreo != asuntocorreo : !asuntocorreo.equals( _cast.asuntocorreo )) {
			return false;
		}
		
		if (asuntocorreoModified != _cast.asuntocorreoModified) {
			return false;
		}
		
		if (plantillacorreo == null ? _cast.plantillacorreo != plantillacorreo : !plantillacorreo.equals( _cast.plantillacorreo )) {
			return false;
		}
		
		if (plantillacorreoModified != _cast.plantillacorreoModified) {
			return false;
		}
		
		if (activarimpresion != _cast.activarimpresion) {
			return false;
		}
		
		if (activarimpresionNull != _cast.activarimpresionNull) {
			return false;
		}
		
		if (activarimpresionModified != _cast.activarimpresionModified) {
			return false;
		}
		
		if (impresorapredeterminada == null ? _cast.impresorapredeterminada != impresorapredeterminada : !impresorapredeterminada.equals( _cast.impresorapredeterminada )) {
			return false;
		}
		
		if (impresorapredeterminadaModified != _cast.impresorapredeterminadaModified) {
			return false;
		}
		
		if (errorPacUltimaConn != _cast.errorPacUltimaConn) {
			return false;
		}
		
		if (errorPacUltimaConnNull != _cast.errorPacUltimaConnNull) {
			return false;
		}
		
		if (errorPacUltimaConnModified != _cast.errorPacUltimaConnModified) {
			return false;
		}
		
		if (rutaEjecutableAdobeReader == null ? _cast.rutaEjecutableAdobeReader != rutaEjecutableAdobeReader : !rutaEjecutableAdobeReader.equals( _cast.rutaEjecutableAdobeReader )) {
			return false;
		}
		
		if (rutaEjecutableAdobeReaderModified != _cast.rutaEjecutableAdobeReaderModified) {
			return false;
		}
		
		if (rutaCarpetaOrigenEcontabilidad == null ? _cast.rutaCarpetaOrigenEcontabilidad != rutaCarpetaOrigenEcontabilidad : !rutaCarpetaOrigenEcontabilidad.equals( _cast.rutaCarpetaOrigenEcontabilidad )) {
			return false;
		}
		
		if (rutaCarpetaOrigenEcontabilidadModified != _cast.rutaCarpetaOrigenEcontabilidadModified) {
			return false;
		}
		
		if (rutaCarpetaDestinoEcontabilidad == null ? _cast.rutaCarpetaDestinoEcontabilidad != rutaCarpetaDestinoEcontabilidad : !rutaCarpetaDestinoEcontabilidad.equals( _cast.rutaCarpetaDestinoEcontabilidad )) {
			return false;
		}
		
		if (rutaCarpetaDestinoEcontabilidadModified != _cast.rutaCarpetaDestinoEcontabilidadModified) {
			return false;
		}
		
		if (ordenLecturaArchivos != _cast.ordenLecturaArchivos) {
			return false;
		}
		
		if (ordenLecturaArchivosModified != _cast.ordenLecturaArchivosModified) {
			return false;
		}
		
		if (lotePdfConcentrado != _cast.lotePdfConcentrado) {
			return false;
		}
		
		if (lotePdfConcentradoModified != _cast.lotePdfConcentradoModified) {
			return false;
		}
		
		if (loteNotificaciones != _cast.loteNotificaciones) {
			return false;
		}
		
		if (loteNotificacionesModified != _cast.loteNotificacionesModified) {
			return false;
		}
		
		if (rutaCarpetaOrigenPaypoint == null ? _cast.rutaCarpetaOrigenPaypoint != rutaCarpetaOrigenPaypoint : !rutaCarpetaOrigenPaypoint.equals( _cast.rutaCarpetaOrigenPaypoint )) {
			return false;
		}
		
		if (rutaCarpetaOrigenPaypointModified != _cast.rutaCarpetaOrigenPaypointModified) {
			return false;
		}
		
		if (rutaCarpetaDestinoPaypoint == null ? _cast.rutaCarpetaDestinoPaypoint != rutaCarpetaDestinoPaypoint : !rutaCarpetaDestinoPaypoint.equals( _cast.rutaCarpetaDestinoPaypoint )) {
			return false;
		}
		
		if (rutaCarpetaDestinoPaypointModified != _cast.rutaCarpetaDestinoPaypointModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idconfifuracion;
		_hashCode = 29 * _hashCode + (idconfifuracionModified ? 1 : 0);
		if (rutaorigenprocesar != null) {
			_hashCode = 29 * _hashCode + rutaorigenprocesar.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rutaorigenprocesarModified ? 1 : 0);
		if (rutacarpetaejecucion != null) {
			_hashCode = 29 * _hashCode + rutacarpetaejecucion.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rutacarpetaejecucionModified ? 1 : 0);
		if (rutacarpetaerrores != null) {
			_hashCode = 29 * _hashCode + rutacarpetaerrores.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rutacarpetaerroresModified ? 1 : 0);
		if (rutacarpetaexitosos != null) {
			_hashCode = 29 * _hashCode + rutacarpetaexitosos.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rutacarpetaexitososModified ? 1 : 0);
		if (rutaorigencancelacionesxml != null) {
			_hashCode = 29 * _hashCode + rutaorigencancelacionesxml.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rutaorigencancelacionesxmlModified ? 1 : 0);
		if (rutadestinocancelacionesxml != null) {
			_hashCode = 29 * _hashCode + rutadestinocancelacionesxml.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rutadestinocancelacionesxmlModified ? 1 : 0);
		if (renamearchivostimbrados != null) {
			_hashCode = 29 * _hashCode + renamearchivostimbrados.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (renamearchivostimbradosModified ? 1 : 0);
		if (ligapac != null) {
			_hashCode = 29 * _hashCode + ligapac.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (ligapacModified ? 1 : 0);
		if (usuariopac != null) {
			_hashCode = 29 * _hashCode + usuariopac.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (usuariopacModified ? 1 : 0);
		if (passpac != null) {
			_hashCode = 29 * _hashCode + passpac.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (passpacModified ? 1 : 0);
		_hashCode = 29 * _hashCode + minutosdemon;
		_hashCode = 29 * _hashCode + (minutosdemonNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (minutosdemonModified ? 1 : 0);
		_hashCode = 29 * _hashCode + enviodecorreo;
		_hashCode = 29 * _hashCode + (enviodecorreoNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (enviodecorreoModified ? 1 : 0);
		if (correoremitente != null) {
			_hashCode = 29 * _hashCode + correoremitente.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (correoremitenteModified ? 1 : 0);
		if (usuarioremitente != null) {
			_hashCode = 29 * _hashCode + usuarioremitente.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (usuarioremitenteModified ? 1 : 0);
		if (dominiosmtp != null) {
			_hashCode = 29 * _hashCode + dominiosmtp.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (dominiosmtpModified ? 1 : 0);
		_hashCode = 29 * _hashCode + puertosmtp;
		_hashCode = 29 * _hashCode + (puertosmtpNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (puertosmtpModified ? 1 : 0);
		if (passwordcorreo != null) {
			_hashCode = 29 * _hashCode + passwordcorreo.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (passwordcorreoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + autenticacionsmtp;
		_hashCode = 29 * _hashCode + (autenticacionsmtpNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (autenticacionsmtpModified ? 1 : 0);
		if (destinatariosfijos != null) {
			_hashCode = 29 * _hashCode + destinatariosfijos.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (destinatariosfijosModified ? 1 : 0);
		if (asuntocorreo != null) {
			_hashCode = 29 * _hashCode + asuntocorreo.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (asuntocorreoModified ? 1 : 0);
		if (plantillacorreo != null) {
			_hashCode = 29 * _hashCode + plantillacorreo.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (plantillacorreoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + activarimpresion;
		_hashCode = 29 * _hashCode + (activarimpresionNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (activarimpresionModified ? 1 : 0);
		if (impresorapredeterminada != null) {
			_hashCode = 29 * _hashCode + impresorapredeterminada.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (impresorapredeterminadaModified ? 1 : 0);
		_hashCode = 29 * _hashCode + errorPacUltimaConn;
		_hashCode = 29 * _hashCode + (errorPacUltimaConnNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (errorPacUltimaConnModified ? 1 : 0);
		if (rutaEjecutableAdobeReader != null) {
			_hashCode = 29 * _hashCode + rutaEjecutableAdobeReader.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rutaEjecutableAdobeReaderModified ? 1 : 0);
		if (rutaCarpetaOrigenEcontabilidad != null) {
			_hashCode = 29 * _hashCode + rutaCarpetaOrigenEcontabilidad.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rutaCarpetaOrigenEcontabilidadModified ? 1 : 0);
		if (rutaCarpetaDestinoEcontabilidad != null) {
			_hashCode = 29 * _hashCode + rutaCarpetaDestinoEcontabilidad.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rutaCarpetaDestinoEcontabilidadModified ? 1 : 0);
		_hashCode = 29 * _hashCode + ordenLecturaArchivos;
		_hashCode = 29 * _hashCode + (ordenLecturaArchivosModified ? 1 : 0);
		_hashCode = 29 * _hashCode + lotePdfConcentrado;
		_hashCode = 29 * _hashCode + (lotePdfConcentradoModified ? 1 : 0);
		_hashCode = 29 * _hashCode + loteNotificaciones;
		_hashCode = 29 * _hashCode + (loteNotificacionesModified ? 1 : 0);
		if (rutaCarpetaOrigenPaypoint != null) {
			_hashCode = 29 * _hashCode + rutaCarpetaOrigenPaypoint.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rutaCarpetaOrigenPaypointModified ? 1 : 0);
		if (rutaCarpetaDestinoPaypoint != null) {
			_hashCode = 29 * _hashCode + rutaCarpetaDestinoPaypoint.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rutaCarpetaDestinoPaypointModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ConfiguracionPk
	 */
	public ConfiguracionPk createPk()
	{
		return new ConfiguracionPk(idconfifuracion);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.fens.desktopMonitor.dto.Configuracion: " );
		ret.append( "idconfifuracion=" + idconfifuracion );
		ret.append( ", rutaorigenprocesar=" + rutaorigenprocesar );
		ret.append( ", rutacarpetaejecucion=" + rutacarpetaejecucion );
		ret.append( ", rutacarpetaerrores=" + rutacarpetaerrores );
		ret.append( ", rutacarpetaexitosos=" + rutacarpetaexitosos );
		ret.append( ", rutaorigencancelacionesxml=" + rutaorigencancelacionesxml );
		ret.append( ", rutadestinocancelacionesxml=" + rutadestinocancelacionesxml );
		ret.append( ", renamearchivostimbrados=" + renamearchivostimbrados );
		ret.append( ", ligapac=" + ligapac );
		ret.append( ", usuariopac=" + usuariopac );
		ret.append( ", passpac=" + passpac );
		ret.append( ", minutosdemon=" + minutosdemon );
		ret.append( ", enviodecorreo=" + enviodecorreo );
		ret.append( ", correoremitente=" + correoremitente );
		ret.append( ", usuarioremitente=" + usuarioremitente );
		ret.append( ", dominiosmtp=" + dominiosmtp );
		ret.append( ", puertosmtp=" + puertosmtp );
		ret.append( ", passwordcorreo=" + passwordcorreo );
		ret.append( ", autenticacionsmtp=" + autenticacionsmtp );
		ret.append( ", destinatariosfijos=" + destinatariosfijos );
		ret.append( ", asuntocorreo=" + asuntocorreo );
		ret.append( ", plantillacorreo=" + plantillacorreo );
		ret.append( ", activarimpresion=" + activarimpresion );
		ret.append( ", impresorapredeterminada=" + impresorapredeterminada );
		ret.append( ", errorPacUltimaConn=" + errorPacUltimaConn );
		ret.append( ", rutaEjecutableAdobeReader=" + rutaEjecutableAdobeReader );
		ret.append( ", rutaCarpetaOrigenEcontabilidad=" + rutaCarpetaOrigenEcontabilidad );
		ret.append( ", rutaCarpetaDestinoEcontabilidad=" + rutaCarpetaDestinoEcontabilidad );
		ret.append( ", ordenLecturaArchivos=" + ordenLecturaArchivos );
		ret.append( ", lotePdfConcentrado=" + lotePdfConcentrado );
		ret.append( ", loteNotificaciones=" + loteNotificaciones );
		ret.append( ", rutaCarpetaOrigenPaypoint=" + rutaCarpetaOrigenPaypoint );
		ret.append( ", rutaCarpetaDestinoPaypoint=" + rutaCarpetaDestinoPaypoint );
		return ret.toString();
	}

}
