/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.fens.desktopMonitor.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the CONFIGURACION table.
 */
public class ConfiguracionPk implements Serializable
{
	protected int idconfifuracion;

	/** 
	 * This attribute represents whether the primitive attribute idconfifuracion is null.
	 */
	protected boolean idconfifuracionNull;

	/** 
	 * Sets the value of idconfifuracion
	 */
	public void setIdconfifuracion(int idconfifuracion)
	{
		this.idconfifuracion = idconfifuracion;
	}

	/** 
	 * Gets the value of idconfifuracion
	 */
	public int getIdconfifuracion()
	{
		return idconfifuracion;
	}

	/**
	 * Method 'ConfiguracionPk'
	 * 
	 */
	public ConfiguracionPk()
	{
	}

	/**
	 * Method 'ConfiguracionPk'
	 * 
	 * @param idconfifuracion
	 */
	public ConfiguracionPk(final int idconfifuracion)
	{
		this.idconfifuracion = idconfifuracion;
	}

	/** 
	 * Sets the value of idconfifuracionNull
	 */
	public void setIdconfifuracionNull(boolean idconfifuracionNull)
	{
		this.idconfifuracionNull = idconfifuracionNull;
	}

	/** 
	 * Gets the value of idconfifuracionNull
	 */
	public boolean isIdconfifuracionNull()
	{
		return idconfifuracionNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ConfiguracionPk)) {
			return false;
		}
		
		final ConfiguracionPk _cast = (ConfiguracionPk) _other;
		if (idconfifuracion != _cast.idconfifuracion) {
			return false;
		}
		
		if (idconfifuracionNull != _cast.idconfifuracionNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idconfifuracion;
		_hashCode = 29 * _hashCode + (idconfifuracionNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.fens.desktopMonitor.dto.ConfiguracionPk: " );
		ret.append( "idconfifuracion=" + idconfifuracion );
		return ret.toString();
	}

}
