/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.fens.desktopMonitor.dto;

import com.fens.desktopMonitor.dao.*;
import com.fens.desktopMonitor.factory.*;
import com.fens.desktopMonitor.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Emisor implements Serializable
{
	/** 
	 * This attribute maps to the column IDEMISOR in the EMISOR table.
	 */
	protected int idemisor;

	/** 
	 * This attribute represents whether the attribute idemisor has been modified since being read from the database.
	 */
	protected boolean idemisorModified = false;

	/** 
	 * This attribute maps to the column RFC in the EMISOR table.
	 */
	protected String rfc;

	/** 
	 * This attribute represents whether the attribute rfc has been modified since being read from the database.
	 */
	protected boolean rfcModified = false;

	/** 
	 * This attribute maps to the column RAZONSOCIAL in the EMISOR table.
	 */
	protected String razonsocial;

	/** 
	 * This attribute represents whether the attribute razonsocial has been modified since being read from the database.
	 */
	protected boolean razonsocialModified = false;

	/** 
	 * This attribute maps to the column NOMBRECOMERCIAL in the EMISOR table.
	 */
	protected String nombrecomercial;

	/** 
	 * This attribute represents whether the attribute nombrecomercial has been modified since being read from the database.
	 */
	protected boolean nombrecomercialModified = false;

	/** 
	 * This attribute maps to the column REGIMENFISCAL in the EMISOR table.
	 */
	protected String regimenfiscal;

	/** 
	 * This attribute represents whether the attribute regimenfiscal has been modified since being read from the database.
	 */
	protected boolean regimenfiscalModified = false;

	/** 
	 * This attribute maps to the column ESTATUS in the EMISOR table.
	 */
	protected int estatus;

	/** 
	 * This attribute represents whether the primitive attribute estatus is null.
	 */
	protected boolean estatusNull = true;

	/** 
	 * This attribute represents whether the attribute estatus has been modified since being read from the database.
	 */
	protected boolean estatusModified = false;

	/** 
	 * This attribute maps to the column REGISTROPATRONAL in the EMISOR table.
	 */
	protected String registropatronal;

	/** 
	 * This attribute represents whether the attribute registropatronal has been modified since being read from the database.
	 */
	protected boolean registropatronalModified = false;

	/** 
	 * This attribute maps to the column PLANTILLACOMPROBANTE in the EMISOR table.
	 */
	protected String plantillacomprobante;

	/** 
	 * This attribute represents whether the attribute plantillacomprobante has been modified since being read from the database.
	 */
	protected boolean plantillacomprobanteModified = false;

	/** 
	 * This attribute maps to the column RUTALOGO in the EMISOR table.
	 */
	protected String rutalogo;

	/** 
	 * This attribute represents whether the attribute rutalogo has been modified since being read from the database.
	 */
	protected boolean rutalogoModified = false;

	/** 
	 * This attribute maps to the column RUTACER in the EMISOR table.
	 */
	protected String rutacer;

	/** 
	 * This attribute represents whether the attribute rutacer has been modified since being read from the database.
	 */
	protected boolean rutacerModified = false;

	/** 
	 * This attribute maps to the column RUTAKEY in the EMISOR table.
	 */
	protected String rutakey;

	/** 
	 * This attribute represents whether the attribute rutakey has been modified since being read from the database.
	 */
	protected boolean rutakeyModified = false;

	/** 
	 * This attribute maps to the column EMISORPASS in the EMISOR table.
	 */
	protected String emisorpass;

	/** 
	 * This attribute represents whether the attribute emisorpass has been modified since being read from the database.
	 */
	protected boolean emisorpassModified = false;

	/** 
	 * This attribute maps to the column PLANTILLANOMINA in the EMISOR table.
	 */
	protected String plantillanomina;

	/** 
	 * This attribute represents whether the attribute plantillanomina has been modified since being read from the database.
	 */
	protected boolean plantillanominaModified = false;

	/** 
	 * This attribute maps to the column PLANTILLA_RETENCIONES in the EMISOR table.
	 */
	protected String plantillaRetenciones;

	/** 
	 * This attribute represents whether the attribute plantillaRetenciones has been modified since being read from the database.
	 */
	protected boolean plantillaRetencionesModified = false;

	/** 
	 * This attribute maps to the column SECTOR_PRIMARIO in the EMISOR table.
	 */
	protected int sectorPrimario;

	/** 
	 * This attribute represents whether the attribute sectorPrimario has been modified since being read from the database.
	 */
	protected boolean sectorPrimarioModified = false;

	/**
	 * Method 'Emisor'
	 * 
	 */
	public Emisor()
	{
	}

	/**
	 * Method 'getIdemisor'
	 * 
	 * @return int
	 */
	public int getIdemisor()
	{
		return idemisor;
	}

	/**
	 * Method 'setIdemisor'
	 * 
	 * @param idemisor
	 */
	public void setIdemisor(int idemisor)
	{
		this.idemisor = idemisor;
		this.idemisorModified = true;
	}

	/** 
	 * Sets the value of idemisorModified
	 */
	public void setIdemisorModified(boolean idemisorModified)
	{
		this.idemisorModified = idemisorModified;
	}

	/** 
	 * Gets the value of idemisorModified
	 */
	public boolean isIdemisorModified()
	{
		return idemisorModified;
	}

	/**
	 * Method 'getRfc'
	 * 
	 * @return String
	 */
	public String getRfc()
	{
		return rfc;
	}

	/**
	 * Method 'setRfc'
	 * 
	 * @param rfc
	 */
	public void setRfc(String rfc)
	{
		this.rfc = rfc;
		this.rfcModified = true;
	}

	/** 
	 * Sets the value of rfcModified
	 */
	public void setRfcModified(boolean rfcModified)
	{
		this.rfcModified = rfcModified;
	}

	/** 
	 * Gets the value of rfcModified
	 */
	public boolean isRfcModified()
	{
		return rfcModified;
	}

	/**
	 * Method 'getRazonsocial'
	 * 
	 * @return String
	 */
	public String getRazonsocial()
	{
		return razonsocial;
	}

	/**
	 * Method 'setRazonsocial'
	 * 
	 * @param razonsocial
	 */
	public void setRazonsocial(String razonsocial)
	{
		this.razonsocial = razonsocial;
		this.razonsocialModified = true;
	}

	/** 
	 * Sets the value of razonsocialModified
	 */
	public void setRazonsocialModified(boolean razonsocialModified)
	{
		this.razonsocialModified = razonsocialModified;
	}

	/** 
	 * Gets the value of razonsocialModified
	 */
	public boolean isRazonsocialModified()
	{
		return razonsocialModified;
	}

	/**
	 * Method 'getNombrecomercial'
	 * 
	 * @return String
	 */
	public String getNombrecomercial()
	{
		return nombrecomercial;
	}

	/**
	 * Method 'setNombrecomercial'
	 * 
	 * @param nombrecomercial
	 */
	public void setNombrecomercial(String nombrecomercial)
	{
		this.nombrecomercial = nombrecomercial;
		this.nombrecomercialModified = true;
	}

	/** 
	 * Sets the value of nombrecomercialModified
	 */
	public void setNombrecomercialModified(boolean nombrecomercialModified)
	{
		this.nombrecomercialModified = nombrecomercialModified;
	}

	/** 
	 * Gets the value of nombrecomercialModified
	 */
	public boolean isNombrecomercialModified()
	{
		return nombrecomercialModified;
	}

	/**
	 * Method 'getRegimenfiscal'
	 * 
	 * @return String
	 */
	public String getRegimenfiscal()
	{
		return regimenfiscal;
	}

	/**
	 * Method 'setRegimenfiscal'
	 * 
	 * @param regimenfiscal
	 */
	public void setRegimenfiscal(String regimenfiscal)
	{
		this.regimenfiscal = regimenfiscal;
		this.regimenfiscalModified = true;
	}

	/** 
	 * Sets the value of regimenfiscalModified
	 */
	public void setRegimenfiscalModified(boolean regimenfiscalModified)
	{
		this.regimenfiscalModified = regimenfiscalModified;
	}

	/** 
	 * Gets the value of regimenfiscalModified
	 */
	public boolean isRegimenfiscalModified()
	{
		return regimenfiscalModified;
	}

	/**
	 * Method 'getEstatus'
	 * 
	 * @return int
	 */
	public int getEstatus()
	{
		return estatus;
	}

	/**
	 * Method 'setEstatus'
	 * 
	 * @param estatus
	 */
	public void setEstatus(int estatus)
	{
		this.estatus = estatus;
		this.estatusNull = false;
		this.estatusModified = true;
	}

	/**
	 * Method 'setEstatusNull'
	 * 
	 * @param value
	 */
	public void setEstatusNull(boolean value)
	{
		this.estatusNull = value;
		this.estatusModified = true;
	}

	/**
	 * Method 'isEstatusNull'
	 * 
	 * @return boolean
	 */
	public boolean isEstatusNull()
	{
		return estatusNull;
	}

	/** 
	 * Sets the value of estatusModified
	 */
	public void setEstatusModified(boolean estatusModified)
	{
		this.estatusModified = estatusModified;
	}

	/** 
	 * Gets the value of estatusModified
	 */
	public boolean isEstatusModified()
	{
		return estatusModified;
	}

	/**
	 * Method 'getRegistropatronal'
	 * 
	 * @return String
	 */
	public String getRegistropatronal()
	{
		return registropatronal;
	}

	/**
	 * Method 'setRegistropatronal'
	 * 
	 * @param registropatronal
	 */
	public void setRegistropatronal(String registropatronal)
	{
		this.registropatronal = registropatronal;
		this.registropatronalModified = true;
	}

	/** 
	 * Sets the value of registropatronalModified
	 */
	public void setRegistropatronalModified(boolean registropatronalModified)
	{
		this.registropatronalModified = registropatronalModified;
	}

	/** 
	 * Gets the value of registropatronalModified
	 */
	public boolean isRegistropatronalModified()
	{
		return registropatronalModified;
	}

	/**
	 * Method 'getPlantillacomprobante'
	 * 
	 * @return String
	 */
	public String getPlantillacomprobante()
	{
		return plantillacomprobante;
	}

	/**
	 * Method 'setPlantillacomprobante'
	 * 
	 * @param plantillacomprobante
	 */
	public void setPlantillacomprobante(String plantillacomprobante)
	{
		this.plantillacomprobante = plantillacomprobante;
		this.plantillacomprobanteModified = true;
	}

	/** 
	 * Sets the value of plantillacomprobanteModified
	 */
	public void setPlantillacomprobanteModified(boolean plantillacomprobanteModified)
	{
		this.plantillacomprobanteModified = plantillacomprobanteModified;
	}

	/** 
	 * Gets the value of plantillacomprobanteModified
	 */
	public boolean isPlantillacomprobanteModified()
	{
		return plantillacomprobanteModified;
	}

	/**
	 * Method 'getRutalogo'
	 * 
	 * @return String
	 */
	public String getRutalogo()
	{
		return rutalogo;
	}

	/**
	 * Method 'setRutalogo'
	 * 
	 * @param rutalogo
	 */
	public void setRutalogo(String rutalogo)
	{
		this.rutalogo = rutalogo;
		this.rutalogoModified = true;
	}

	/** 
	 * Sets the value of rutalogoModified
	 */
	public void setRutalogoModified(boolean rutalogoModified)
	{
		this.rutalogoModified = rutalogoModified;
	}

	/** 
	 * Gets the value of rutalogoModified
	 */
	public boolean isRutalogoModified()
	{
		return rutalogoModified;
	}

	/**
	 * Method 'getRutacer'
	 * 
	 * @return String
	 */
	public String getRutacer()
	{
		return rutacer;
	}

	/**
	 * Method 'setRutacer'
	 * 
	 * @param rutacer
	 */
	public void setRutacer(String rutacer)
	{
		this.rutacer = rutacer;
		this.rutacerModified = true;
	}

	/** 
	 * Sets the value of rutacerModified
	 */
	public void setRutacerModified(boolean rutacerModified)
	{
		this.rutacerModified = rutacerModified;
	}

	/** 
	 * Gets the value of rutacerModified
	 */
	public boolean isRutacerModified()
	{
		return rutacerModified;
	}

	/**
	 * Method 'getRutakey'
	 * 
	 * @return String
	 */
	public String getRutakey()
	{
		return rutakey;
	}

	/**
	 * Method 'setRutakey'
	 * 
	 * @param rutakey
	 */
	public void setRutakey(String rutakey)
	{
		this.rutakey = rutakey;
		this.rutakeyModified = true;
	}

	/** 
	 * Sets the value of rutakeyModified
	 */
	public void setRutakeyModified(boolean rutakeyModified)
	{
		this.rutakeyModified = rutakeyModified;
	}

	/** 
	 * Gets the value of rutakeyModified
	 */
	public boolean isRutakeyModified()
	{
		return rutakeyModified;
	}

	/**
	 * Method 'getEmisorpass'
	 * 
	 * @return String
	 */
	public String getEmisorpass()
	{
		return emisorpass;
	}

	/**
	 * Method 'setEmisorpass'
	 * 
	 * @param emisorpass
	 */
	public void setEmisorpass(String emisorpass)
	{
		this.emisorpass = emisorpass;
		this.emisorpassModified = true;
	}

	/** 
	 * Sets the value of emisorpassModified
	 */
	public void setEmisorpassModified(boolean emisorpassModified)
	{
		this.emisorpassModified = emisorpassModified;
	}

	/** 
	 * Gets the value of emisorpassModified
	 */
	public boolean isEmisorpassModified()
	{
		return emisorpassModified;
	}

	/**
	 * Method 'getPlantillanomina'
	 * 
	 * @return String
	 */
	public String getPlantillanomina()
	{
		return plantillanomina;
	}

	/**
	 * Method 'setPlantillanomina'
	 * 
	 * @param plantillanomina
	 */
	public void setPlantillanomina(String plantillanomina)
	{
		this.plantillanomina = plantillanomina;
		this.plantillanominaModified = true;
	}

	/** 
	 * Sets the value of plantillanominaModified
	 */
	public void setPlantillanominaModified(boolean plantillanominaModified)
	{
		this.plantillanominaModified = plantillanominaModified;
	}

	/** 
	 * Gets the value of plantillanominaModified
	 */
	public boolean isPlantillanominaModified()
	{
		return plantillanominaModified;
	}

	/**
	 * Method 'getPlantillaRetenciones'
	 * 
	 * @return String
	 */
	public String getPlantillaRetenciones()
	{
		return plantillaRetenciones;
	}

	/**
	 * Method 'setPlantillaRetenciones'
	 * 
	 * @param plantillaRetenciones
	 */
	public void setPlantillaRetenciones(String plantillaRetenciones)
	{
		this.plantillaRetenciones = plantillaRetenciones;
		this.plantillaRetencionesModified = true;
	}

	/** 
	 * Sets the value of plantillaRetencionesModified
	 */
	public void setPlantillaRetencionesModified(boolean plantillaRetencionesModified)
	{
		this.plantillaRetencionesModified = plantillaRetencionesModified;
	}

	/** 
	 * Gets the value of plantillaRetencionesModified
	 */
	public boolean isPlantillaRetencionesModified()
	{
		return plantillaRetencionesModified;
	}

	/**
	 * Method 'getSectorPrimario'
	 * 
	 * @return int
	 */
	public int getSectorPrimario()
	{
		return sectorPrimario;
	}

	/**
	 * Method 'setSectorPrimario'
	 * 
	 * @param sectorPrimario
	 */
	public void setSectorPrimario(int sectorPrimario)
	{
		this.sectorPrimario = sectorPrimario;
		this.sectorPrimarioModified = true;
	}

	/** 
	 * Sets the value of sectorPrimarioModified
	 */
	public void setSectorPrimarioModified(boolean sectorPrimarioModified)
	{
		this.sectorPrimarioModified = sectorPrimarioModified;
	}

	/** 
	 * Gets the value of sectorPrimarioModified
	 */
	public boolean isSectorPrimarioModified()
	{
		return sectorPrimarioModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Emisor)) {
			return false;
		}
		
		final Emisor _cast = (Emisor) _other;
		if (idemisor != _cast.idemisor) {
			return false;
		}
		
		if (idemisorModified != _cast.idemisorModified) {
			return false;
		}
		
		if (rfc == null ? _cast.rfc != rfc : !rfc.equals( _cast.rfc )) {
			return false;
		}
		
		if (rfcModified != _cast.rfcModified) {
			return false;
		}
		
		if (razonsocial == null ? _cast.razonsocial != razonsocial : !razonsocial.equals( _cast.razonsocial )) {
			return false;
		}
		
		if (razonsocialModified != _cast.razonsocialModified) {
			return false;
		}
		
		if (nombrecomercial == null ? _cast.nombrecomercial != nombrecomercial : !nombrecomercial.equals( _cast.nombrecomercial )) {
			return false;
		}
		
		if (nombrecomercialModified != _cast.nombrecomercialModified) {
			return false;
		}
		
		if (regimenfiscal == null ? _cast.regimenfiscal != regimenfiscal : !regimenfiscal.equals( _cast.regimenfiscal )) {
			return false;
		}
		
		if (regimenfiscalModified != _cast.regimenfiscalModified) {
			return false;
		}
		
		if (estatus != _cast.estatus) {
			return false;
		}
		
		if (estatusNull != _cast.estatusNull) {
			return false;
		}
		
		if (estatusModified != _cast.estatusModified) {
			return false;
		}
		
		if (registropatronal == null ? _cast.registropatronal != registropatronal : !registropatronal.equals( _cast.registropatronal )) {
			return false;
		}
		
		if (registropatronalModified != _cast.registropatronalModified) {
			return false;
		}
		
		if (plantillacomprobante == null ? _cast.plantillacomprobante != plantillacomprobante : !plantillacomprobante.equals( _cast.plantillacomprobante )) {
			return false;
		}
		
		if (plantillacomprobanteModified != _cast.plantillacomprobanteModified) {
			return false;
		}
		
		if (rutalogo == null ? _cast.rutalogo != rutalogo : !rutalogo.equals( _cast.rutalogo )) {
			return false;
		}
		
		if (rutalogoModified != _cast.rutalogoModified) {
			return false;
		}
		
		if (rutacer == null ? _cast.rutacer != rutacer : !rutacer.equals( _cast.rutacer )) {
			return false;
		}
		
		if (rutacerModified != _cast.rutacerModified) {
			return false;
		}
		
		if (rutakey == null ? _cast.rutakey != rutakey : !rutakey.equals( _cast.rutakey )) {
			return false;
		}
		
		if (rutakeyModified != _cast.rutakeyModified) {
			return false;
		}
		
		if (emisorpass == null ? _cast.emisorpass != emisorpass : !emisorpass.equals( _cast.emisorpass )) {
			return false;
		}
		
		if (emisorpassModified != _cast.emisorpassModified) {
			return false;
		}
		
		if (plantillanomina == null ? _cast.plantillanomina != plantillanomina : !plantillanomina.equals( _cast.plantillanomina )) {
			return false;
		}
		
		if (plantillanominaModified != _cast.plantillanominaModified) {
			return false;
		}
		
		if (plantillaRetenciones == null ? _cast.plantillaRetenciones != plantillaRetenciones : !plantillaRetenciones.equals( _cast.plantillaRetenciones )) {
			return false;
		}
		
		if (plantillaRetencionesModified != _cast.plantillaRetencionesModified) {
			return false;
		}
		
		if (sectorPrimario != _cast.sectorPrimario) {
			return false;
		}
		
		if (sectorPrimarioModified != _cast.sectorPrimarioModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idemisor;
		_hashCode = 29 * _hashCode + (idemisorModified ? 1 : 0);
		if (rfc != null) {
			_hashCode = 29 * _hashCode + rfc.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rfcModified ? 1 : 0);
		if (razonsocial != null) {
			_hashCode = 29 * _hashCode + razonsocial.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (razonsocialModified ? 1 : 0);
		if (nombrecomercial != null) {
			_hashCode = 29 * _hashCode + nombrecomercial.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (nombrecomercialModified ? 1 : 0);
		if (regimenfiscal != null) {
			_hashCode = 29 * _hashCode + regimenfiscal.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (regimenfiscalModified ? 1 : 0);
		_hashCode = 29 * _hashCode + estatus;
		_hashCode = 29 * _hashCode + (estatusNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (estatusModified ? 1 : 0);
		if (registropatronal != null) {
			_hashCode = 29 * _hashCode + registropatronal.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (registropatronalModified ? 1 : 0);
		if (plantillacomprobante != null) {
			_hashCode = 29 * _hashCode + plantillacomprobante.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (plantillacomprobanteModified ? 1 : 0);
		if (rutalogo != null) {
			_hashCode = 29 * _hashCode + rutalogo.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rutalogoModified ? 1 : 0);
		if (rutacer != null) {
			_hashCode = 29 * _hashCode + rutacer.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rutacerModified ? 1 : 0);
		if (rutakey != null) {
			_hashCode = 29 * _hashCode + rutakey.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (rutakeyModified ? 1 : 0);
		if (emisorpass != null) {
			_hashCode = 29 * _hashCode + emisorpass.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (emisorpassModified ? 1 : 0);
		if (plantillanomina != null) {
			_hashCode = 29 * _hashCode + plantillanomina.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (plantillanominaModified ? 1 : 0);
		if (plantillaRetenciones != null) {
			_hashCode = 29 * _hashCode + plantillaRetenciones.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (plantillaRetencionesModified ? 1 : 0);
		_hashCode = 29 * _hashCode + sectorPrimario;
		_hashCode = 29 * _hashCode + (sectorPrimarioModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return EmisorPk
	 */
	public EmisorPk createPk()
	{
		return new EmisorPk(idemisor);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.fens.desktopMonitor.dto.Emisor: " );
		ret.append( "idemisor=" + idemisor );
		ret.append( ", rfc=" + rfc );
		ret.append( ", razonsocial=" + razonsocial );
		ret.append( ", nombrecomercial=" + nombrecomercial );
		ret.append( ", regimenfiscal=" + regimenfiscal );
		ret.append( ", estatus=" + estatus );
		ret.append( ", registropatronal=" + registropatronal );
		ret.append( ", plantillacomprobante=" + plantillacomprobante );
		ret.append( ", rutalogo=" + rutalogo );
		ret.append( ", rutacer=" + rutacer );
		ret.append( ", rutakey=" + rutakey );
		ret.append( ", emisorpass=" + emisorpass );
		ret.append( ", plantillanomina=" + plantillanomina );
		ret.append( ", plantillaRetenciones=" + plantillaRetenciones );
		ret.append( ", sectorPrimario=" + sectorPrimario );
		return ret.toString();
	}

}
