/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.fens.desktopMonitor.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the ESTATUS table.
 */
public class EstatusPk implements Serializable
{
	protected int idestatus;

	/** 
	 * This attribute represents whether the primitive attribute idestatus is null.
	 */
	protected boolean idestatusNull;

	/** 
	 * Sets the value of idestatus
	 */
	public void setIdestatus(int idestatus)
	{
		this.idestatus = idestatus;
	}

	/** 
	 * Gets the value of idestatus
	 */
	public int getIdestatus()
	{
		return idestatus;
	}

	/**
	 * Method 'EstatusPk'
	 * 
	 */
	public EstatusPk()
	{
	}

	/**
	 * Method 'EstatusPk'
	 * 
	 * @param idestatus
	 */
	public EstatusPk(final int idestatus)
	{
		this.idestatus = idestatus;
	}

	/** 
	 * Sets the value of idestatusNull
	 */
	public void setIdestatusNull(boolean idestatusNull)
	{
		this.idestatusNull = idestatusNull;
	}

	/** 
	 * Gets the value of idestatusNull
	 */
	public boolean isIdestatusNull()
	{
		return idestatusNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EstatusPk)) {
			return false;
		}
		
		final EstatusPk _cast = (EstatusPk) _other;
		if (idestatus != _cast.idestatus) {
			return false;
		}
		
		if (idestatusNull != _cast.idestatusNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idestatus;
		_hashCode = 29 * _hashCode + (idestatusNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.fens.desktopMonitor.dto.EstatusPk: " );
		ret.append( "idestatus=" + idestatus );
		return ret.toString();
	}

}
