/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.fens.desktopMonitor.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the NOMINA table.
 */
public class NominaPk implements Serializable
{
	protected int idnomina;

	/** 
	 * This attribute represents whether the primitive attribute idnomina is null.
	 */
	protected boolean idnominaNull;

	/** 
	 * Sets the value of idnomina
	 */
	public void setIdnomina(int idnomina)
	{
		this.idnomina = idnomina;
	}

	/** 
	 * Gets the value of idnomina
	 */
	public int getIdnomina()
	{
		return idnomina;
	}

	/**
	 * Method 'NominaPk'
	 * 
	 */
	public NominaPk()
	{
	}

	/**
	 * Method 'NominaPk'
	 * 
	 * @param idnomina
	 */
	public NominaPk(final int idnomina)
	{
		this.idnomina = idnomina;
	}

	/** 
	 * Sets the value of idnominaNull
	 */
	public void setIdnominaNull(boolean idnominaNull)
	{
		this.idnominaNull = idnominaNull;
	}

	/** 
	 * Gets the value of idnominaNull
	 */
	public boolean isIdnominaNull()
	{
		return idnominaNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof NominaPk)) {
			return false;
		}
		
		final NominaPk _cast = (NominaPk) _other;
		if (idnomina != _cast.idnomina) {
			return false;
		}
		
		if (idnominaNull != _cast.idnominaNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idnomina;
		_hashCode = 29 * _hashCode + (idnominaNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.fens.desktopMonitor.dto.NominaPk: " );
		ret.append( "idnomina=" + idnomina );
		return ret.toString();
	}

}
