/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.fens.desktopMonitor.dto;

import com.fens.desktopMonitor.dao.*;
import com.fens.desktopMonitor.factory.*;
import com.fens.desktopMonitor.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Ubicacionfiscal implements Serializable
{
	/** 
	 * This attribute maps to the column IDUBICACIONFISCAL in the UBICACIONFISCAL table.
	 */
	protected int idubicacionfiscal;

	/** 
	 * This attribute represents whether the attribute idubicacionfiscal has been modified since being read from the database.
	 */
	protected boolean idubicacionfiscalModified = false;

	/** 
	 * This attribute maps to the column IDEMISOR in the UBICACIONFISCAL table.
	 */
	protected int idemisor;

	/** 
	 * This attribute represents whether the attribute idemisor has been modified since being read from the database.
	 */
	protected boolean idemisorModified = false;

	/** 
	 * This attribute maps to the column CALLE in the UBICACIONFISCAL table.
	 */
	protected String calle;

	/** 
	 * This attribute represents whether the attribute calle has been modified since being read from the database.
	 */
	protected boolean calleModified = false;

	/** 
	 * This attribute maps to the column NUMINT in the UBICACIONFISCAL table.
	 */
	protected String numint;

	/** 
	 * This attribute represents whether the attribute numint has been modified since being read from the database.
	 */
	protected boolean numintModified = false;

	/** 
	 * This attribute maps to the column NUMEXT in the UBICACIONFISCAL table.
	 */
	protected String numext;

	/** 
	 * This attribute represents whether the attribute numext has been modified since being read from the database.
	 */
	protected boolean numextModified = false;

	/** 
	 * This attribute maps to the column COLONIA in the UBICACIONFISCAL table.
	 */
	protected String colonia;

	/** 
	 * This attribute represents whether the attribute colonia has been modified since being read from the database.
	 */
	protected boolean coloniaModified = false;

	/** 
	 * This attribute maps to the column CODIGOPOSTAL in the UBICACIONFISCAL table.
	 */
	protected String codigopostal;

	/** 
	 * This attribute represents whether the attribute codigopostal has been modified since being read from the database.
	 */
	protected boolean codigopostalModified = false;

	/** 
	 * This attribute maps to the column PAIS in the UBICACIONFISCAL table.
	 */
	protected String pais;

	/** 
	 * This attribute represents whether the attribute pais has been modified since being read from the database.
	 */
	protected boolean paisModified = false;

	/** 
	 * This attribute maps to the column ESTADO in the UBICACIONFISCAL table.
	 */
	protected String estado;

	/** 
	 * This attribute represents whether the attribute estado has been modified since being read from the database.
	 */
	protected boolean estadoModified = false;

	/** 
	 * This attribute maps to the column MUNICIPIO in the UBICACIONFISCAL table.
	 */
	protected String municipio;

	/** 
	 * This attribute represents whether the attribute municipio has been modified since being read from the database.
	 */
	protected boolean municipioModified = false;

	/**
	 * Method 'Ubicacionfiscal'
	 * 
	 */
	public Ubicacionfiscal()
	{
	}

	/**
	 * Method 'getIdubicacionfiscal'
	 * 
	 * @return int
	 */
	public int getIdubicacionfiscal()
	{
		return idubicacionfiscal;
	}

	/**
	 * Method 'setIdubicacionfiscal'
	 * 
	 * @param idubicacionfiscal
	 */
	public void setIdubicacionfiscal(int idubicacionfiscal)
	{
		this.idubicacionfiscal = idubicacionfiscal;
		this.idubicacionfiscalModified = true;
	}

	/** 
	 * Sets the value of idubicacionfiscalModified
	 */
	public void setIdubicacionfiscalModified(boolean idubicacionfiscalModified)
	{
		this.idubicacionfiscalModified = idubicacionfiscalModified;
	}

	/** 
	 * Gets the value of idubicacionfiscalModified
	 */
	public boolean isIdubicacionfiscalModified()
	{
		return idubicacionfiscalModified;
	}

	/**
	 * Method 'getIdemisor'
	 * 
	 * @return int
	 */
	public int getIdemisor()
	{
		return idemisor;
	}

	/**
	 * Method 'setIdemisor'
	 * 
	 * @param idemisor
	 */
	public void setIdemisor(int idemisor)
	{
		this.idemisor = idemisor;
		this.idemisorModified = true;
	}

	/** 
	 * Sets the value of idemisorModified
	 */
	public void setIdemisorModified(boolean idemisorModified)
	{
		this.idemisorModified = idemisorModified;
	}

	/** 
	 * Gets the value of idemisorModified
	 */
	public boolean isIdemisorModified()
	{
		return idemisorModified;
	}

	/**
	 * Method 'getCalle'
	 * 
	 * @return String
	 */
	public String getCalle()
	{
		return calle;
	}

	/**
	 * Method 'setCalle'
	 * 
	 * @param calle
	 */
	public void setCalle(String calle)
	{
		this.calle = calle;
		this.calleModified = true;
	}

	/** 
	 * Sets the value of calleModified
	 */
	public void setCalleModified(boolean calleModified)
	{
		this.calleModified = calleModified;
	}

	/** 
	 * Gets the value of calleModified
	 */
	public boolean isCalleModified()
	{
		return calleModified;
	}

	/**
	 * Method 'getNumint'
	 * 
	 * @return String
	 */
	public String getNumint()
	{
		return numint;
	}

	/**
	 * Method 'setNumint'
	 * 
	 * @param numint
	 */
	public void setNumint(String numint)
	{
		this.numint = numint;
		this.numintModified = true;
	}

	/** 
	 * Sets the value of numintModified
	 */
	public void setNumintModified(boolean numintModified)
	{
		this.numintModified = numintModified;
	}

	/** 
	 * Gets the value of numintModified
	 */
	public boolean isNumintModified()
	{
		return numintModified;
	}

	/**
	 * Method 'getNumext'
	 * 
	 * @return String
	 */
	public String getNumext()
	{
		return numext;
	}

	/**
	 * Method 'setNumext'
	 * 
	 * @param numext
	 */
	public void setNumext(String numext)
	{
		this.numext = numext;
		this.numextModified = true;
	}

	/** 
	 * Sets the value of numextModified
	 */
	public void setNumextModified(boolean numextModified)
	{
		this.numextModified = numextModified;
	}

	/** 
	 * Gets the value of numextModified
	 */
	public boolean isNumextModified()
	{
		return numextModified;
	}

	/**
	 * Method 'getColonia'
	 * 
	 * @return String
	 */
	public String getColonia()
	{
		return colonia;
	}

	/**
	 * Method 'setColonia'
	 * 
	 * @param colonia
	 */
	public void setColonia(String colonia)
	{
		this.colonia = colonia;
		this.coloniaModified = true;
	}

	/** 
	 * Sets the value of coloniaModified
	 */
	public void setColoniaModified(boolean coloniaModified)
	{
		this.coloniaModified = coloniaModified;
	}

	/** 
	 * Gets the value of coloniaModified
	 */
	public boolean isColoniaModified()
	{
		return coloniaModified;
	}

	/**
	 * Method 'getCodigopostal'
	 * 
	 * @return String
	 */
	public String getCodigopostal()
	{
		return codigopostal;
	}

	/**
	 * Method 'setCodigopostal'
	 * 
	 * @param codigopostal
	 */
	public void setCodigopostal(String codigopostal)
	{
		this.codigopostal = codigopostal;
		this.codigopostalModified = true;
	}

	/** 
	 * Sets the value of codigopostalModified
	 */
	public void setCodigopostalModified(boolean codigopostalModified)
	{
		this.codigopostalModified = codigopostalModified;
	}

	/** 
	 * Gets the value of codigopostalModified
	 */
	public boolean isCodigopostalModified()
	{
		return codigopostalModified;
	}

	/**
	 * Method 'getPais'
	 * 
	 * @return String
	 */
	public String getPais()
	{
		return pais;
	}

	/**
	 * Method 'setPais'
	 * 
	 * @param pais
	 */
	public void setPais(String pais)
	{
		this.pais = pais;
		this.paisModified = true;
	}

	/** 
	 * Sets the value of paisModified
	 */
	public void setPaisModified(boolean paisModified)
	{
		this.paisModified = paisModified;
	}

	/** 
	 * Gets the value of paisModified
	 */
	public boolean isPaisModified()
	{
		return paisModified;
	}

	/**
	 * Method 'getEstado'
	 * 
	 * @return String
	 */
	public String getEstado()
	{
		return estado;
	}

	/**
	 * Method 'setEstado'
	 * 
	 * @param estado
	 */
	public void setEstado(String estado)
	{
		this.estado = estado;
		this.estadoModified = true;
	}

	/** 
	 * Sets the value of estadoModified
	 */
	public void setEstadoModified(boolean estadoModified)
	{
		this.estadoModified = estadoModified;
	}

	/** 
	 * Gets the value of estadoModified
	 */
	public boolean isEstadoModified()
	{
		return estadoModified;
	}

	/**
	 * Method 'getMunicipio'
	 * 
	 * @return String
	 */
	public String getMunicipio()
	{
		return municipio;
	}

	/**
	 * Method 'setMunicipio'
	 * 
	 * @param municipio
	 */
	public void setMunicipio(String municipio)
	{
		this.municipio = municipio;
		this.municipioModified = true;
	}

	/** 
	 * Sets the value of municipioModified
	 */
	public void setMunicipioModified(boolean municipioModified)
	{
		this.municipioModified = municipioModified;
	}

	/** 
	 * Gets the value of municipioModified
	 */
	public boolean isMunicipioModified()
	{
		return municipioModified;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Ubicacionfiscal)) {
			return false;
		}
		
		final Ubicacionfiscal _cast = (Ubicacionfiscal) _other;
		if (idubicacionfiscal != _cast.idubicacionfiscal) {
			return false;
		}
		
		if (idubicacionfiscalModified != _cast.idubicacionfiscalModified) {
			return false;
		}
		
		if (idemisor != _cast.idemisor) {
			return false;
		}
		
		if (idemisorModified != _cast.idemisorModified) {
			return false;
		}
		
		if (calle == null ? _cast.calle != calle : !calle.equals( _cast.calle )) {
			return false;
		}
		
		if (calleModified != _cast.calleModified) {
			return false;
		}
		
		if (numint == null ? _cast.numint != numint : !numint.equals( _cast.numint )) {
			return false;
		}
		
		if (numintModified != _cast.numintModified) {
			return false;
		}
		
		if (numext == null ? _cast.numext != numext : !numext.equals( _cast.numext )) {
			return false;
		}
		
		if (numextModified != _cast.numextModified) {
			return false;
		}
		
		if (colonia == null ? _cast.colonia != colonia : !colonia.equals( _cast.colonia )) {
			return false;
		}
		
		if (coloniaModified != _cast.coloniaModified) {
			return false;
		}
		
		if (codigopostal == null ? _cast.codigopostal != codigopostal : !codigopostal.equals( _cast.codigopostal )) {
			return false;
		}
		
		if (codigopostalModified != _cast.codigopostalModified) {
			return false;
		}
		
		if (pais == null ? _cast.pais != pais : !pais.equals( _cast.pais )) {
			return false;
		}
		
		if (paisModified != _cast.paisModified) {
			return false;
		}
		
		if (estado == null ? _cast.estado != estado : !estado.equals( _cast.estado )) {
			return false;
		}
		
		if (estadoModified != _cast.estadoModified) {
			return false;
		}
		
		if (municipio == null ? _cast.municipio != municipio : !municipio.equals( _cast.municipio )) {
			return false;
		}
		
		if (municipioModified != _cast.municipioModified) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idubicacionfiscal;
		_hashCode = 29 * _hashCode + (idubicacionfiscalModified ? 1 : 0);
		_hashCode = 29 * _hashCode + idemisor;
		_hashCode = 29 * _hashCode + (idemisorModified ? 1 : 0);
		if (calle != null) {
			_hashCode = 29 * _hashCode + calle.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (calleModified ? 1 : 0);
		if (numint != null) {
			_hashCode = 29 * _hashCode + numint.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (numintModified ? 1 : 0);
		if (numext != null) {
			_hashCode = 29 * _hashCode + numext.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (numextModified ? 1 : 0);
		if (colonia != null) {
			_hashCode = 29 * _hashCode + colonia.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (coloniaModified ? 1 : 0);
		if (codigopostal != null) {
			_hashCode = 29 * _hashCode + codigopostal.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (codigopostalModified ? 1 : 0);
		if (pais != null) {
			_hashCode = 29 * _hashCode + pais.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (paisModified ? 1 : 0);
		if (estado != null) {
			_hashCode = 29 * _hashCode + estado.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (estadoModified ? 1 : 0);
		if (municipio != null) {
			_hashCode = 29 * _hashCode + municipio.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (municipioModified ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return UbicacionfiscalPk
	 */
	public UbicacionfiscalPk createPk()
	{
		return new UbicacionfiscalPk(idubicacionfiscal);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.fens.desktopMonitor.dto.Ubicacionfiscal: " );
		ret.append( "idubicacionfiscal=" + idubicacionfiscal );
		ret.append( ", idemisor=" + idemisor );
		ret.append( ", calle=" + calle );
		ret.append( ", numint=" + numint );
		ret.append( ", numext=" + numext );
		ret.append( ", colonia=" + colonia );
		ret.append( ", codigopostal=" + codigopostal );
		ret.append( ", pais=" + pais );
		ret.append( ", estado=" + estado );
		ret.append( ", municipio=" + municipio );
		return ret.toString();
	}

}
