/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.fens.desktopMonitor.views;

import com.fens.desktopMonitor.Control.series_action;
import com.fens.desktopMonitor.bo.EmisorBO;
import com.fens.desktopMonitor.bo.TipoComprobanteBO;
import com.fens.desktopMonitor.dto.Emisor;
import com.fens.desktopMonitor.dto.Tipocomprobante;
import com.fens.desktopMonitor.jdbc.Conexion;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ISCesar
 */
public class Series extends javax.swing.JFrame {
    
    private int idEmisor = -1;
    private Emisor emisorDto;
    private series_action action;
    Connection conn = Conexion.getConn();

    /**
     * Creates new form Series
     */
    public Series(int idEmisor) {
        this.idEmisor = idEmisor;
        initComponents();
        initOtherComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatosSerie = new javax.swing.JPanel();
        lblIdSerie = new javax.swing.JLabel();
        txtIdSerie = new javax.swing.JTextField();
        lblIdSerie1 = new javax.swing.JLabel();
        txtNombreSerie = new javax.swing.JTextField();
        lblIdSerie2 = new javax.swing.JLabel();
        txtRangoInicio = new javax.swing.JTextField();
        lblIdSerie3 = new javax.swing.JLabel();
        txtRangoFin = new javax.swing.JTextField();
        lblIdSerie4 = new javax.swing.JLabel();
        txtUltimoFolio = new javax.swing.JTextField();
        lblIdSerie6 = new javax.swing.JLabel();
        lblIdSerie7 = new javax.swing.JLabel();
        comboEstatusSerie = new javax.swing.JComboBox();
        comboTipoComprobante = new javax.swing.JComboBox();
        cmdGuardarEmisor = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSeries = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }

        };

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Series del Emisor");
        setResizable(false);

        lblIdSerie.setText("ID Serie:");

        txtIdSerie.setEditable(false);

        lblIdSerie1.setText("Nombre:");

        lblIdSerie2.setText("Rango Inicio:");

        lblIdSerie3.setText("Rango Fin:");

        lblIdSerie4.setText("Ultimo Folio Usado:");

        lblIdSerie6.setText("Estatus Serie:");

        lblIdSerie7.setText("Tipo Comprobante:");

        cmdGuardarEmisor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fens/desktopMonitor/images/Save-icon.png"))); // NOI18N
        cmdGuardarEmisor.setText("Guardar");
        cmdGuardarEmisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarEmisorActionPerformed(evt);
            }
        });

        cmdEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fens/desktopMonitor/images/Windows-Close-Program-icon.png"))); // NOI18N
        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosSerieLayout = new javax.swing.GroupLayout(jPanelDatosSerie);
        jPanelDatosSerie.setLayout(jPanelDatosSerieLayout);
        jPanelDatosSerieLayout.setHorizontalGroup(
            jPanelDatosSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosSerieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosSerieLayout.createSequentialGroup()
                        .addGroup(jPanelDatosSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosSerieLayout.createSequentialGroup()
                                .addComponent(lblIdSerie4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUltimoFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosSerieLayout.createSequentialGroup()
                                .addGroup(jPanelDatosSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelDatosSerieLayout.createSequentialGroup()
                                        .addComponent(lblIdSerie3)
                                        .addGap(49, 49, 49))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosSerieLayout.createSequentialGroup()
                                        .addComponent(lblIdSerie2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanelDatosSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRangoFin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRangoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)))
                        .addGap(75, 75, 75)
                        .addComponent(cmdGuardarEmisor)
                        .addGap(33, 33, 33)
                        .addComponent(cmdEliminar))
                    .addGroup(jPanelDatosSerieLayout.createSequentialGroup()
                        .addGroup(jPanelDatosSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdSerie)
                            .addComponent(lblIdSerie1))
                        .addGap(59, 59, 59)
                        .addGroup(jPanelDatosSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanelDatosSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelDatosSerieLayout.createSequentialGroup()
                                .addComponent(lblIdSerie6)
                                .addGap(43, 43, 43)
                                .addComponent(comboEstatusSerie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelDatosSerieLayout.createSequentialGroup()
                                .addComponent(lblIdSerie7)
                                .addGap(18, 18, 18)
                                .addComponent(comboTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosSerieLayout.setVerticalGroup(
            jPanelDatosSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosSerieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdSerie)
                    .addComponent(txtIdSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdSerie6)
                    .addComponent(comboEstatusSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdSerie1)
                    .addComponent(txtNombreSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdSerie7)
                    .addComponent(comboTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdSerie2)
                    .addComponent(txtRangoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdSerie3)
                    .addComponent(txtRangoFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdSerie4)
                    .addComponent(txtUltimoFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdGuardarEmisor)
                    .addComponent(cmdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableSeries.setAutoCreateRowSorter(true);
        jTableSeries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSeries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSeriesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSeries);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatosSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDatosSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdGuardarEmisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarEmisorActionPerformed

        //Instanciamos conotrolador
        action = new series_action(this);
        try {
            //Accion
            action.guardaSerie(idEmisor);
        } catch (Exception ex) {
           ex.printStackTrace();
           JOptionPane.showMessageDialog(null,"Ocurrio un error al guardar el registro:\n " + ex.toString(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_cmdGuardarEmisorActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed

        int rowSelected;
        
        try{
             rowSelected = jTableSeries.getSelectedRow(); /* Obtenemos fila seleccionada*/            
        
        
            int idSerie = Integer.parseInt(txtIdSerie.getText()); /* Fila id */
            String nombreSerie = txtNombreSerie.getText(); /* Fila nombre */
            
             //Instanciamos conotrolador
            action = new series_action(this);
            
            int dialogResult = JOptionPane.showConfirmDialog (null, "¿Deseas eliminar la Serie '" + nombreSerie + "'?","Advertencia",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){ 
                try {                

                    action.eliminarSerie(idSerie, idEmisor); /* Estatus = -1 -> Eliminado*/

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,"Ocurrio un error al eliminar el registro:\n " + ex.toString(),"Error",JOptionPane.ERROR_MESSAGE);
                }  
            
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No ha seleccionado una Serie a eliminar en el listado.");
        }

    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void jTableSeriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSeriesMouseClicked
        if (evt.getClickCount() == 2) { /* Si da doble clic sobre tabla */
            
            int rowSelected = jTableSeries.getSelectedRow(); /* Obtenemos fila seleccionada*/
            
            int idSerie = Integer.parseInt(jTableSeries.getValueAt(rowSelected, 0).toString()); /* Fila id */
            
            /* Carga serie seleccionada */
            
            //Instanciamos controlador
            action = new series_action(this);
             
            try {
                action.cargaSerie(idSerie);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "No se encontraron datos del Emisor seleccionado. ");
            }
            
            
           
        }
    }//GEN-LAST:event_jTableSeriesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Series.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Series.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Series.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Series.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Series series = new Series(1);
                series.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cmdEliminar;
    public javax.swing.JButton cmdGuardarEmisor;
    public javax.swing.JComboBox comboEstatusSerie;
    public javax.swing.JComboBox comboTipoComprobante;
    private javax.swing.JPanel jPanelDatosSerie;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSeries;
    private javax.swing.JLabel lblIdSerie;
    private javax.swing.JLabel lblIdSerie1;
    private javax.swing.JLabel lblIdSerie2;
    private javax.swing.JLabel lblIdSerie3;
    private javax.swing.JLabel lblIdSerie4;
    private javax.swing.JLabel lblIdSerie6;
    private javax.swing.JLabel lblIdSerie7;
    public javax.swing.JTextField txtIdSerie;
    public javax.swing.JTextField txtNombreSerie;
    public javax.swing.JTextField txtRangoFin;
    public javax.swing.JTextField txtRangoInicio;
    public javax.swing.JTextField txtUltimoFolio;
    // End of variables declaration//GEN-END:variables

    
    private void initOtherComponentes(){
        
        //Centramos Form en Pantalla
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    
        EmisorBO emisorBO = new EmisorBO(this.conn,idEmisor);
        this.emisorDto = emisorBO.getEmisor();
        if (this.emisorDto!=null){
            this.setTitle(this.getTitle() + " " + emisorDto.getRfc());
        }
        
        /*LLenamos tabla con series */    
        try{
            jTableSeries.setModel(series_action.fillSeries(idEmisor)); /*  Seteamos modelo a tabla */
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al cargar tabla de Series:\n" + e.toString(),"Error",JOptionPane.ERROR_MESSAGE); 
        }
        
        //Completamos control Combo de selección Estatus Serie
        comboEstatusSerie.addItem("Selecciona...");          
        comboEstatusSerie.addItem("ACTIVO");
        comboEstatusSerie.addItem("INACTIVO");
        
        //Completamos control Combo de selección Tipo Comprobante
        TipoComprobanteBO tipoComprobanteBO = new TipoComprobanteBO(null);
        Tipocomprobante[] tipoComprobantes = tipoComprobanteBO.findTipocomprobantes(-1, 0, 0, "");
        comboTipoComprobante.addItem("Selecciona...");
        for (Tipocomprobante item :  tipoComprobantes){
            comboTipoComprobante.addItem(item);
        }
        
    }
    
    public void limpiaFormulario(JPanel panel) {
        // Component componentes[] = getContentPane().getComponents(); 
        Component componentes[] = panel.getComponents();
        /* Conseguimos todos los componentes del contenedor utilizado */
        for (Component componente : componentes) {
            String clase = componente.getClass().getName();
            if (clase.equals("javax.swing.JTextField")) {
                JTextField tmp = (JTextField) componente;
                tmp.setText("");
            }
            if (clase.equals("javax.swing.JPasswordField")) {
                JPasswordField tmp = (JPasswordField) componente;
                tmp.setText("");
            }
            if (clase.equals("javax.swing.JComboBox")) {
                JComboBox tmp = (JComboBox) componente;
                tmp.setSelectedIndex(0);
            }
            /*
            if(clase.equals("javax.swing.JCheckBox"))
            {
            JCheckBox tmp = (JCheckBox)componentes[i];
            tmp.setSelected(false);
            }      */
        }
    }

    public int getIdEmisor() {
        return idEmisor;
    }

    public void setIdEmisor(int idEmisor) {
        this.idEmisor = idEmisor;
    }

    public JTable getjTableSeries() {
        return jTableSeries;
    }

    public JPanel getjPanelDatosSerie() {
        return jPanelDatosSerie;
    }

    
    
}
